### ISSUE TITLE
v3.0.0-rc:  array_key_exists(): The first argument should be either a string or an integer

### ISSUE THREAD

**Issue by lkppo** [phpDocumentor/phpDocumentor#2282] opened 2020-02-10 02:04 UTC
We use phpdoc to build the API manul of [WIKINDX](https://sourceforge.net/projects/wikindx/).

We have a build script (https://sourceforge.net/p/wikindx/code/HEAD/tree/release/make.php) that call phpdoc (as a phar file) and issue this command:

`php "C:\devel\wikindx\release\..\tools\phpDocumentor.phar" -vvv -c phpdoc.xml --cache-folder ..\phpdoc_cache --title="WIKINDX Documentation trunk" 2>&1`

## Your environment

* Version used: 3.0.0-rc
* Install method: PHAR
* php version : 7.2.6
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): Windows 7
* Link to your project: https://sourceforge.net/projects/wikindx

The original configuration is:
```
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor>
	<title>WIKINDX Documentation</title>
	<parser>
		<encoding>utf8</encoding>
		<target>docs/manual</target>
		<default-package-name>wikindx</default-package-name>
		<extensions>
			<extension>php</extension>
		</extensions>
	</parser>
	<transformer>
		<target>docs/manual</target>
	</transformer>
	<files>
		<directory>.</directory>
		<ignore>cache/*</ignore>
		<ignore>data/*</ignore>
		<ignore>components/*</ignore>
		<ignore>core/javascript/*</ignore>
		<ignore>core/modules/*</ignore>
		<ignore>core/tiny_mce/*.js</ignore>
		<ignore>core/tiny_mce/*.txt</ignore>
		<ignore>core/tiny_mce/langs/*</ignore>
		<ignore>core/tiny_mce/plugins/*</ignore>
		<ignore>core/tiny_mce/themes/*</ignore>
		<ignore>core/tiny_mce/utils/*</ignore>
		<ignore>docs/*</ignore>
		<ignore>dbschema/*</ignore>
		<ignore>.php_cs.cache</ignore>
		<ignore>cmsprint.php</ignore>
		<ignore>config.php</ignore>
		<ignore>config.php.dist</ignore>
		<ignore>dump-repairkit-schema.php</ignore>
		<ignore>index.php</ignore>
		<ignore>make-languages.php</ignore>
		<ignore>make-md-docs.php</ignore>
		<ignore>phpdoc.xml</ignore>
		<ignore>php-fmt-dev.php</ignore>
		<ignore>rss.php</ignore>
		<ignore>sign-components.php</ignore>
		<ignore>sitemap.php</ignore>
	</files>
	<logging>
		<level>warn</level>
		<paths>
			<default>../phpdoc_{DATE}.log</default>
			<errors>../phpdoc_{DATE}.errors.log</errors>
		</paths>
	</logging>
</phpdocumentor>
```

I tried to convert to:

```
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor configVersion="3.0">
  <paths>
    <output>docs/manual</output>
  </paths>
  <!--Zero or more repetitions:-->
  <version number="3.0">
    <!--Optional:-->
    <folder>latest</folder>
    <!--Zero or more repetitions:-->
    <api format="php">
      <source dsn=".">
        <!--1 or more repetitions:-->
        <path>.</path>
      </source>
      <!--Optional:-->
      <ignore hidden="true" symlinks="true">
		<path>.php_cs.cache</path>
		<path>cache/*</path>
		<path>cmsprint.php</path>
		<path>components/*</path>
		<path>config.php.dist</path>
		<path>config.php</path>
		<path>core/javascript/*</path>
		<path>core/modules/*</path>
		<path>core/tiny_mce/*.js</path>
		<path>core/tiny_mce/*.txt</path>
		<path>core/tiny_mce/langs/*</path>
		<path>core/tiny_mce/plugins/*</path>
		<path>core/tiny_mce/themes/*</path>
		<path>core/tiny_mce/utils/*</path>
		<path>data/*</path>
		<path>dbschema/*</path>
		<path>docs/*</path>
		<path>dump-repairkit-schema.php</path>
		<path>index.php</path>
		<path>make-languages.php</path>
		<path>make-md-docs.php</path>
		<path>phpdoc.xml</path>
		<path>php-fmt-dev.php</path>
		<path>rss.php</path>
		<path>sign-components.php</path>
		<path>sitemap.php</path>
      </ignore>
      <!--Optional:-->
      <extensions>
        <!--1 or more repetitions:-->
        <extension>php</extension>
      </extensions>
      <!--Optional:-->
      <visibility>private</visibility>
      <!--Optional:-->
      <default-package-name>wikindx</default-package-name>
      <!--Optional:-->
      <include-source>true</include-source>
      <!--Optional:-->
      <markers>
        <!--1 or more repetitions:-->
        <marker>TODO</marker>
        <marker>FIXME</marker>
      </markers>
    </api>
  </version>
</phpdocumentor>
```

I hit a crash with some errors and don't know if my config is the culprit or if there a real bugs:

```
Box Requirements Checker
========================

> Using PHP 7.2.26
> PHP is using the following php.ini file:
  C:\winnmp\conf\php.ini

> Checking Box requirements:
  ✔ The application requires the version ">=7.2.5" or greater.
  ✔ The application requires the extension "dom".
  ✔ The application requires the extension "iconv".
  ✔ The application requires the extension "json".
  ✔ The package "league/uri" requires the extension "json".
  ✔ The package "league/uri-interfaces" requires the extension "json".
  ✔ The package "scrivo/highlight.php" requires the extension "json".
  ✔ The application requires the extension "libxml".
  ✔ The application requires the extension "simplexml".
  ✔ The application requires the extension "zlib".
  ✔ The package "league/flysystem" requires the extension "fileinfo".
  ✔ The package "league/uri" requires the extension "fileinfo".
  ✔ The package "nikic/php-parser" requires the extension "tokenizer".
  ✔ The package "phpdocumentor/reflection-docblock" requires the extension
"filter".
  ✔ The package "symfony/framework-bundle" requires the extension "xml".


 [OK] Your system is ready to run the application.



Warning: array_key_exists(): The first argument should be either a string or an integer in phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/config/Definition/PrototypedArrayNode.php on line 251
phpDocumentor v3.0.0-rc

02:50:55 NOTICE    [app] Using the configuration file at: phpdoc.xml
02:50:55 NOTICE    [app] Using the configuration file at: phpdoc.xml
02:50:55 WARNING   [php] Warning: array_key_exists(): The first argument should be either a string or an integer
[
  "exception" => ErrorException {
    #message: "Warning: array_key_exists(): The first argument should be either a string or an integer"
    #code: 0
    #file: "phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/config/Definition/PrototypedArrayNode.php"
    #line: 251
    #severity: E_WARNING
    trace: {
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/config/Definition/PrototypedArrayNode.php:251 {
        Symfony\Component\Config\Definition\PrototypedArrayNode->normalizeValue($value)^
        ›
        › if (\array_key_exists($k, $normalized)) {
        › $ex = new DuplicateKeyException(sprintf('Duplicate key "%s" for path "%s".', $k, $this->getPath()));
      }
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/config/Definition/BaseNode.php:366 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/config/Definition/ArrayNode.php:284 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/config/Definition/BaseNode.php:366 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/config/Definition/Processor.php:34 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/config/Definition/Processor.php:50 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Configuration/SymfonyConfigFactory.php:102 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Configuration/SymfonyConfigFactory.php:71 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Configuration/SymfonyConfigFactory.php:51 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Configuration/ConfigurationFactory.php:96 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Pipeline/Stage/Configure.php:109 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Pipeline/Stage/Configure.php:74 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/FingersCrossedProcessor.php:11 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php:34 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php:39 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/FingersCrossedProcessor.php:11 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php:34 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php:39 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Console/Command/Project/RunCommand.php:280 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/console/Command/Command.php:255 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/console/Application.php:943 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/framework-bundle/Console/Application.php:97 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/console/Application.php:265 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/framework-bundle/Console/Application.php:83 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/console/Application.php:141 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/bin/phpdoc:43 { …}
      C:\devel\wikindx\tools\phpDocumentor.phar:14 { …}
    }
  }
]
02:50:55 WARNING   [php] Warning: array_key_exists(): The first argument should be either a string or an integer
[
  "exception" => ErrorException {
    #message: "Warning: array_key_exists(): The first argument should be either a string or an integer"
    #code: 0
    #file: "phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/config/Definition/PrototypedArrayNode.php"
    #line: 251
    #severity: E_WARNING
    trace: {
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/config/Definition/PrototypedArrayNode.php:251 {
        Symfony\Component\Config\Definition\PrototypedArrayNode->normalizeValue($value)^
        ›
        › if (\array_key_exists($k, $normalized)) {
        › $ex = new DuplicateKeyException(sprintf('Duplicate key "%s" for path "%s".', $k, $this->getPath()));
      }
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/config/Definition/BaseNode.php:366 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/config/Definition/ArrayNode.php:284 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/config/Definition/BaseNode.php:366 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/config/Definition/Processor.php:34 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/config/Definition/Processor.php:50 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Configuration/SymfonyConfigFactory.php:102 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Configuration/SymfonyConfigFactory.php:71 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Configuration/SymfonyConfigFactory.php:51 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Configuration/ConfigurationFactory.php:96 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Pipeline/Stage/Configure.php:109 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Pipeline/Stage/Configure.php:74 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/FingersCrossedProcessor.php:11 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php:34 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php:39 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/FingersCrossedProcessor.php:11 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php:34 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php:39 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Console/Command/Project/RunCommand.php:280 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/console/Command/Command.php:255 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/console/Application.php:943 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/framework-bundle/Console/Application.php:97 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/console/Application.php:265 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/framework-bundle/Console/Application.php:83 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/console/Application.php:141 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/bin/phpdoc:43 { …}
      C:\devel\wikindx\tools\phpDocumentor.phar:14 { …}
    }
  }
]
02:50:55 INFO      [app] Logging to: C:/devel/wikindx/release/trunk/phpdoc_cache
02:50:55 INFO      [app] Logging to: C:/devel/wikindx/release/trunk/phpdoc_cache
02:50:55 ERROR     [console] Error thrown while running command "-vvv -c "phpdoc.xml" --cache-folder "..\phpdoc_cache" --title="WIKINDX Documentation trunk". Message: "Argument 1 passed to phpDocumentor\Descriptor\VersionDescriptor::__construct() must be of the type string, integer given, called in phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Pipeline/Stage/InitializeBuilderFromConfig.php on line 51"
[
  "exception" => TypeError {
    #message: "Argument 1 passed to phpDocumentor\Descriptor\VersionDescriptor::__construct() must be of the type string, integer given, called in phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Pipeline/Stage/InitializeBuilderFromConfig.php on line 51"
    #code: 0
    #file: "phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Descriptor/VersionDescriptor.php"
    #line: 27
    trace: {
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Descriptor/VersionDescriptor.php:27 {
        phpDocumentor\Descriptor\VersionDescriptor->__construct(string $number, Collection $documentationSets)^
        ›
        › public function __construct(string $number, Collection $documentationSets)
        › {
      }
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Pipeline/Stage/InitializeBuilderFromConfig.php:51 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/FingersCrossedProcessor.php:11 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php:34 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php:39 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/FingersCrossedProcessor.php:11 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php:34 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php:39 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Console/Command/Project/RunCommand.php:280 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/console/Command/Command.php:255 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/console/Application.php:943 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/framework-bundle/Console/Application.php:97 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/console/Application.php:265 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/framework-bundle/Console/Application.php:83 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/console/Application.php:141 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/bin/phpdoc:43 { …}
      C:\devel\wikindx\tools\phpDocumentor.phar:14 { …}
    }
  },
  "command" => "-vvv -c "phpdoc.xml" --cache-folder "..\phpdoc_cache" --title="WIKINDX Documentation trunk"",
  "message" => "Argument 1 passed to phpDocumentor\Descriptor\VersionDescriptor::__construct() must be of the type string, integer given, called in phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Pipeline/Stage/InitializeBuilderFromConfig.php on line 51"
]
02:50:55 ERROR     [console] Error thrown while running command "-vvv -c "phpdoc.xml" --cache-folder "..\phpdoc_cache" --title="WIKINDX Documentation trunk". Message: "Argument 1 passed to phpDocumentor\Descriptor\VersionDescriptor::__construct() must be of the type string, integer given, called in phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Pipeline/Stage/InitializeBuilderFromConfig.php on line 51"
[
  "exception" => TypeError {
    #message: "Argument 1 passed to phpDocumentor\Descriptor\VersionDescriptor::__construct() must be of the type string, integer given, called in phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Pipeline/Stage/InitializeBuilderFromConfig.php on line 51"
    #code: 0
    #file: "phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Descriptor/VersionDescriptor.php"
    #line: 27
    trace: {
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Descriptor/VersionDescriptor.php:27 {
        phpDocumentor\Descriptor\VersionDescriptor->__construct(string $number, Collection $documentationSets)^
        ›
        › public function __construct(string $number, Collection $documentationSets)
        › {
      }
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Pipeline/Stage/InitializeBuilderFromConfig.php:51 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/FingersCrossedProcessor.php:11 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php:34 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php:39 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/FingersCrossedProcessor.php:11 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php:34 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php:39 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Console/Command/Project/RunCommand.php:280 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/console/Command/Command.php:255 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/console/Application.php:943 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/framework-bundle/Console/Application.php:97 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/console/Application.php:265 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/framework-bundle/Console/Application.php:83 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/console/Application.php:141 { …}
      phar://C:/devel/wikindx/tools/phpDocumentor.phar/bin/phpdoc:43 { …}
      C:\devel\wikindx\tools\phpDocumentor.phar:14 { …}
    }
  },
  "command" => "-vvv -c "phpdoc.xml" --cache-folder "..\phpdoc_cache" --title="WIKINDX Documentation trunk"",
  "message" => "Argument 1 passed to phpDocumentor\Descriptor\VersionDescriptor::__construct() must be of the type string, integer given, called in phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Pipeline/Stage/InitializeBuilderFromConfig.php on line 51"
]
02:50:56 DEBUG     [console] Command "-vvv -c "phpdoc.xml" --cache-folder "..\phpdoc_cache" --title="WIKINDX Documentation trunk" exited with code "1"
[
  "command" => "-vvv -c "phpdoc.xml" --cache-folder "..\phpdoc_cache" --title="WIKINDX Documentation trunk"",
  "code" => 1
]
02:50:56 DEBUG     [console] Command "-vvv -c "phpdoc.xml" --cache-folder "..\phpdoc_cache" --title="WIKINDX Documentation trunk" exited with code "1"
[
  "command" => "-vvv -c "phpdoc.xml" --cache-folder "..\phpdoc_cache" --title="WIKINDX Documentation trunk"",
  "code" => 1
]

In VersionDescriptor.php line 27:

  [TypeError]
  Argument 1 passed to phpDocumentor\Descriptor\VersionDescriptor::__construct() must be of the type string, integer given, called in phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocu
  mentor/Pipeline/Stage/InitializeBuilderFromConfig.php on line 51


Exception trace:
  at phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Descriptor/VersionDescriptor.php:27
 phpDocumentor\Descriptor\VersionDescriptor->__construct() at phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Pipeline/Stage/InitializeBuilderFromConfig.php:51
 phpDocumentor\Pipeline\Stage\InitializeBuilderFromConfig->__invoke() at phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/FingersCrossedProcessor.php:11
 League\Pipeline\FingersCrossedProcessor->process() at phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php:34
 League\Pipeline\Pipeline->process() at phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php:39
 League\Pipeline\Pipeline->__invoke() at phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/FingersCrossedProcessor.php:11
 League\Pipeline\FingersCrossedProcessor->process() at phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php:34
 League\Pipeline\Pipeline->process() at phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php:39
 League\Pipeline\Pipeline->__invoke() at phar://C:/devel/wikindx/tools/phpDocumentor.phar/src/phpDocumentor/Console/Command/Project/RunCommand.php:280
 phpDocumentor\Console\Command\Project\RunCommand->execute() at phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/console/Application.php:943
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/framework-bundle/Console/Application.php:97
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/console/Application.php:265
 Symfony\Component\Console\Application->doRun() at phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/framework-bundle/Console/Application.php:83
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at phar://C:/devel/wikindx/tools/phpDocumentor.phar/vendor/symfony/console/Application.php:141
 Symfony\Component\Console\Application->run() at phar://C:/devel/wikindx/tools/phpDocumentor.phar/bin/phpdoc:43
 require() at C:\devel\wikindx\tools\phpDocumentor.phar:14
```

**Comment by jaapio** [comment] 2020-03-06 22:37
The problem is that somehow the version number you are specifying is converted to an integer. so 
`<version number="3.0">` gets converted to `3` this results in the error you are getting. 
change it to `<version number="v3.0">` will make phpdoc work. however, I think this should be fixed on our side. 

Just casting the integer to a string in code will work. but the version number used will be `3` and not `3.0` as you would expect. So that's not a solution. I'm still searching for a way to solve this.

**Comment by lkppo** [comment] 2020-03-07 00:27
Ok, I will give it a test., but I'm a little puzzled because the [ref. doc](https://github.com/phpDocumentor/phpDocumentor/blob/master/docs/references/configuration.rst) and [phpdoc.dist.xml](https://github.com/phpDocumentor/phpDocumentor/blob/master/phpdoc.dist.xml) say:

`<version number="3.0.0">`

**Comment by jaapio** [comment] 2020-03-07 08:02
That's because `3.0.0` is a string. Php cannot convert this to an int :unamused: but it should not be converted anyways so that's what I need to find

**Comment by lkppo** [comment] 2020-03-07 12:40
I have encountered vicious bugs with XML on other projects. It is not so much a good solution for configuration. Since phpdoc is a dev tool. for dev. using a structure in PHP would be simpler and completely accessible.

I don't fully understand the need to have <phpdocumentor configVersion="3.0"> and <version number="3.0">. If the second is a config file version it should be enough.

Instead of fighting the parser you could change version number to an integer incremented by 1 each time you change the configuration file format. After you know that the software version X.Y.Z can parse versions N to P of the config file and you make it explicit in your code and in the doc.

You could yet parse N and rewrite it to P, because you keep the spec of each version.

**Comment by jaapio** [comment] 2020-03-07 12:49
The version number is not a version of the config but of your docs. In the future we want to have support for multiple versions in the same documentation set. Which would allow us to generate the docs for a library at once and create a list of the versions.

Xml is the best way to go, because it allows us to provide a proper schema to validate the config in your editor and during the execution.

**Comment by lkppo** [comment] 2020-03-07 13:17
Ok. I would have called this tag <project version="">. Maybe changing the attribute to tag will solve the problem if the raw value of the attribute cannot be read. Like that:

```
<version>
    <number>latest</number>
    <folder>latest</folder>
    <api> <!-- optional --> </api>
    <guide> <!-- optional --> </guide>
</version>
```

> Xml is the best way to go, because it allows us to provide a proper schema to validate the config in your editor and during the execution.

If you want real validation of the configuration you need a DTD scheme.

**Comment by jaapio** [comment] 2020-03-08 15:23
The issue has been fixed in master, but with a workaround, since this is a bug in symfony config IMO. So I reported an issue there to see if they are willing to fix this. 

If so the work around can be reverted.

**Closed by jaapio** 2020-03-08 15:23 UTC

**Comment by lkppo** [comment] 2020-03-08 15:38
Thank you very much for this correction. I will be happy to test when I publish a next rc, unless there is a nighly build.

**Comment by jaapio** [comment] 2020-03-08 15:44
There is a nightly build please consult the Readme how to download it.
Thanks for trying this out, and your feedback upon now.

**Comment by lkppo** [comment] 2020-03-08 16:03
Sorry don't see that. I give it a try with the last build. This exception is fixed but I hit an other. I open an other issue.

**Comment by lkppo** [comment] 2020-03-08 16:22
<version number="3.0.0"> is ok.
<version number="3.0"> trigger yet this exception.

**Comment by jaapio** [comment] 2020-03-09 07:57
That's caused by symfony, That's why I created an issue for them
