### ISSUE TITLE
phpDoc3 failing when ran in the same way I used to run phpDoc2

### ISSUE THREAD

**Issue by Atulin** [phpDocumentor/phpDocumentor#2022] opened 2018-09-24 01:56 UTC
## Expected Behavior

```
php phpdoc2.phar run -d ./ -t ./docs --ignore .git/,.idea/,node_modules/,semantic/,tinymce/,vendor/ --cache-folder ../phpdoc_cache
```
command generates the docs in PHPD3 as it used to in PHPD2

## Actual Behavior

``run`` needs to be added after ``phpdoc.phar``, and even then, the whole thing crashes with
```
E:\Software\Laragon\www\phbooru>php phpdoc2.phar run -d ./ -t ./docs --ignore .git/,.idea/,node_modules/,semantic/,tinymce/,vendor/ --cache-folder ../phpdoc_cache
01:48:57 ERROR     [console] Error thrown while running command "run -d "./" -t "./docs" --ignore ".git/,.idea/,node_modules/,semantic/,tinymce/,vendor/" --cache-folder "../phpdoc_cache"". Message: "Cannot use object of type phpDocumentor\DomainModel\Path as array" ["error" => Error { …},"command" => "run -d "./" -t "./docs" --ignore ".git/,.idea/,node_modules/,semantic/,tinymce/,vendor/" --cache-folder "../phpdoc_cache"","message" => "Cannot use object of type phpDocumentor\DomainModel\Path as array"] []
01:48:57 ERROR     [console] Error thrown while running command "run -d "./" -t "./docs" --ignore ".git/,.idea/,node_modules/,semantic/,tinymce/,vendor/" --cache-folder "../phpdoc_cache". Message: "Cannot use object of type phpDocumentor\DomainModel\Path as array" ["error" => Error { …},"command" => "run -d "./" -t "./docs" --ignore ".git/,.idea/,node_modules/,semantic/,tinymce/,vendor/" --cache-folder "../phpdoc_cache"","message" => "Cannot use object of type phpDocumentor\DomainModel\Path as array"] []

In Filesystem.php line 614:

  Cannot use object of type phpDocumentor\DomainModel\Path as array


project:run [-t|--target [TARGET]] [--cache-folder [CACHE-FOLDER]] [-f|--filename [FILENAME]] [-d|--directory [DIRECTORY]] [--encoding [ENCODING]] [--extensions [EXTENSIONS]] [-i|--ignore [IGNORE]] [--ignore-tags [IGNORE-TAGS]] [--hidden] [--ignore-symlinks] [-m|--markers [MARKERS]] [--title [TITLE]] [--force] [--validate] [--visibility [VISIBILITY]] [--defaultpackagename [DEFAULTPACKAGENAME]] [--sourcecode] [-p|--progressbar] [--template [TEMPLATE]] [--parseprivate] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [-c|--config [CONFIG]] [--log [LOG]] [--] <command>


E:\Software\Laragon\www\phbooru>pause
```

## Steps to Reproduce the Problem

  1. Run phpDoc 3 in the described way
  2. Run phpDoc 2 in the exact same way (except without ``run``) to confirm that this one's working nicely
  3. Notice, that "This first alpha release should be a drop-in replacement for phpDocumentor v2" might not exactly hold true

## Your environment

* **Version used:** 3.0.0-alpha2, compared to whichever version is on the website
* **Install method:** phar
* **php version:** 7.1.5
* **Operating system and version** Win10 x64

**Comment by mvriel** [comment] 2018-09-24 03:29
Hi @Atulin,

Thanks for your report! The necessary addition of the run command is something I fixed yesterday on the develop branch; so that should be resolved now. Regarding the second error, I need to check with @jaapio whether he is addressing this issue since he is reworking part of how we deal with multiple folders. 

Although I am afraid this is a legitimate bug in how we parse the ignore paths.

**Comment by jaapio** [comment] 2018-10-21 06:59
Hi @Atulin,

Yesterday we released a new version of phpdoc v3. Could you please check if this new version fixes the issue you were facing?

Thanks for your feedback.

**Comment by Atulin** [comment] 2018-10-21 14:43
Running
```
php phpdoc.phar -d ./ -t docs --ignore .git/,.idea/,node_modules/,semantic/,tinymce/,vendor/ --cache-folder ../phpdoc_cache
```
Still tries to parse ``vendor/`` directory.

File structure:
![image](https://user-images.githubusercontent.com/11233299/47268366-31899400-d550-11e8-84c2-0d019e3dc0b5.png)

**Comment by jaapio** [comment] 2018-10-21 14:48
Ok, we will investigate what is going on. I expect that when you define multiple ignore parameters instead of one comma separated it will work. But I need to check what is exactly going on in this case

**Comment by Atulin** [comment] 2018-10-21 14:59
A little bit of an update: I let the script run regardless, and it did finish. It created the ``./docs`` folder, although it's empty.

**Comment by jaapio** [comment] 2018-10-21 18:11
I checked this myself on linux. And I think the command below should work for you as well

`php phpdoc.phar -d ./ -t docs --ignore .git/ -i .idea/  -i node_modules/ -i semantic/ -i tinymce/ -i vendor/ --cache-folder ../phpdoc_cache`

I don't have a windows device available to check this. You could try to omit the trailing `/` to be sure the directory separator is not an issue. However I don't expect that to be the issue.

**Comment by Atulin** [comment] 2018-10-21 19:56
Most of everything was parsed successfuly (a few errors on ``\array[Type]`` annotations), only got this thrown at the end:

```
[2018-10-21 19:33:02] console.ERROR: Error thrown while running command "-d "./" -t docs --ignore "
.git/" -i ".idea/" -i "node_modules/" -i "semantic/" -i "tinymce/" -i "vendor/" --cache-folder "../
phpdoc_cache"". Message: "Return value of phpDocumentor\Descriptor\Tag\BaseTypes\TypedAbstract::get
Types() must implement interface phpDocumentor\Reflection\Type or be null, instance of phpDocumento
r\Descriptor\Collection returned" {"exception":"[object] (TypeError(code: 0): Return value of phpDo
cumentor\\Descriptor\\Tag\\BaseTypes\\TypedAbstract::getTypes() must implement interface phpDocumen
tor\\Reflection\\Type or be null, instance of phpDocumentor\\Descriptor\\Collection returned at pha
r://E:/Software/Laragon/www/omnibus/phpdoc.phar/src/phpDocumentor/Descriptor/Tag/BaseTypes/TypedAbs
tract.php:43)","command":"-d \"./\" -t docs --ignore \".git/\" -i \".idea/\" -i \"node_modules/\" -
i \"semantic/\" -i \"tinymce/\" -i \"vendor/\" --cache-folder \"../phpdoc_cache\"","message":"Retur
n value of phpDocumentor\\Descriptor\\Tag\\BaseTypes\\TypedAbstract::getTypes() must implement inte
rface phpDocumentor\\Reflection\\Type or be null, instance of phpDocumentor\\Descriptor\\Collection
 returned"} []
[2018-10-21 19:33:02] console.ERROR: Error thrown while running command "{command}". Message: "{mes
sage}" {"exception":"[object] (TypeError(code: 0): Return value of phpDocumentor\\Descriptor\\Tag\\
BaseTypes\\TypedAbstract::getTypes() must implement interface phpDocumentor\\Reflection\\Type or be
 null, instance of phpDocumentor\\Descriptor\\Collection returned at phar://E:/Software/Laragon/www
/omnibus/phpdoc.phar/src/phpDocumentor/Descriptor/Tag/BaseTypes/TypedAbstract.php:43)","command":"-
d \"./\" -t docs --ignore \".git/\" -i \".idea/\" -i \"node_modules/\" -i \"semantic/\" -i \"tinymc
e/\" -i \"vendor/\" --cache-folder \"../phpdoc_cache\"","message":"Return value of phpDocumentor\\D
escriptor\\Tag\\BaseTypes\\TypedAbstract::getTypes() must implement interface phpDocumentor\\Reflec
tion\\Type or be null, instance of phpDocumentor\\Descriptor\\Collection returned"} []

In TypedAbstract.php line 43:

  Return value of phpDocumentor\Descriptor\Tag\BaseTypes\TypedAbstract::getTypes() must implemen
  t interface phpDocumentor\Reflection\Type or be null, instance of phpDocumentor\Descriptor\Col
  lection returned


project:run [-t|--target [TARGET]] [--cache-folder [CACHE-FOLDER]] [-f|--filename [FILENAME]] [-d|-
-directory [DIRECTORY]] [--encoding [ENCODING]] [--extensions [EXTENSIONS]] [-i|--ignore [IGNORE]]
[--ignore-tags [IGNORE-TAGS]] [--hidden] [--ignore-symlinks] [-m|--markers [MARKERS]] [--title [TIT
LE]] [--force] [--validate] [--visibility [VISIBILITY]] [--defaultpackagename [DEFAULTPACKAGENAME]]
 [--sourcecode] [-p|--progressbar] [--template [TEMPLATE]] [--parseprivate] [-h|--help] [-q|--quiet
] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-c|--config [CON
FIG]] [--log [LOG]] [-e|--env ENV] [--no-debug] [--] <command>

```

**Comment by Atulin** [comment] 2018-10-26 04:13
Any update on the topic? The issue still has the "needs author update" label. If any more info is needed, do let me know.

**Comment by Atulin** [comment] 2018-11-14 02:19
So, @jaapio , how's it going? Need any more info or testing on my side?

**Comment by jaapio** [comment] 2018-11-14 11:30
I didn't have time yet to have a look at this issue.

**Comment by jaapio** [comment] 2020-01-02 20:36
@Atulin first of all my apologies that it took so long before I was able to get back to you. I had a long period past year that I didn't have the energy to work on issues for phpdocumentor.

However we as a team have done a recap and we are now wrapping up to get more speed and progress to the project again. So this is the moment where I'm back to get your reported issue fixed. 

A lot has been changed in the past weeks. since you did not include a link to your project I'm not able to test your run again. It would be very nice if you  are able to test our latest build https://github.com/phpDocumentor/phpDocumentor/suites/382073002/artifacts/922879 

please let me know if you have any issues remaining. I will close this issue in a few weeks without any response. Since It is open for so long that I don't remember what the actual issue was.

**Comment by Atulin** [comment] 2020-01-02 22:03
Again, ran it with
```
php phpdoc.phar -d ./ -t docs --ignore .git/,.idea/,node_modules/,semantic/,tinymce/,vendor/ --cache-folder ../phpdoc_cache
```
in a project with the following structure:
![image](https://user-images.githubusercontent.com/11233299/71695569-cc1b6f00-2db2-11ea-9eb9-5ced2c32a5c7.png)

And the first thing that I immediately noticed, is that it decided to ignore the ignore parameter and scan all files, including vendor:
```
phpDocumentor 8bbe8ca

Parsing files
  651/6055 [===>------------------------]  10%21:53:52 ALERT     [app]   Unable to parse file "vendor/jms/serializer/tests/Metadata/Driver/XmlDriverTest.php", an error was detected: The tag "@expectedExceptionMessage [FATAL] Start tag expected, '<' not found" does not seem to be wellformed, please check it for errors
21:53:52 ALERT     [app]   Unable to parse file "vendor/jms/serializer/tests/Metadata/Driver/XmlDriverTest.php", an error was detected: The tag "@expectedExceptionMessage [FATAL] Start tag expected, '<' not found" does not seem to be wellformed, please check it for errors
  836/6055 [===>------------------------]  13%21:54:17 ALERT     [app]   Unable to parse file "vendor/monolog/monolog/tests/Monolog/Formatter/FlowdockFormatterTest.php", an error was detected: The tag "@ covers Monolog\Formatter\FlowdockFormatter::formatBatch" does not seem to be wellformed, please check it for errors
21:54:17 ALERT     [app]   Unable to parse file "vendor/monolog/monolog/tests/Monolog/Formatter/FlowdockFormatterTest.php", an error was detected: The tag "@ covers Monolog\Formatter\FlowdockFormatter::formatBatch" does not seem to be wellformed, please check it for errors
 1030/6055 [====>-----------------------]  17%
```

Then I added `./` before every ignored directory:
```
php phpdoc.phar -d ./ -t docs --ignore ./.git/,./.idea/,./node_modules/,./semantic/,./tinymce/,./vendor/ --cache-folder ../phpdoc_cache
```
and it again went on to try and parse all 6055 files, including vendor:
```
phpDocumentor 8bbe8ca

Parsing files
 3782/6055 [=================>----------]  62%22:02:43 ALERT     [app]   Unable to parse file "vendor/twig/twig/src/Extension/CoreExtension.php", an error was detected: "" is not a valid Fqsen.
22:02:43 ALERT     [app]   Unable to parse file "vendor/twig/twig/src/Extension/CoreExtension.php", an error was detected: "" is not a valid Fqsen.
 3788/6055 [=================>----------]  62%22:02:43 ALERT     [app]   Unable to parse file "vendor/twig/twig/src/Extension/DebugExtension.php", an error was detected: "" is not a valid Fqsen.
22:02:43 ALERT     [app]   Unable to parse file "vendor/twig/twig/src/Extension/DebugExtension.php", an error was detected: "" is not a valid Fqsen.
22:02:43 ALERT     [app]   Unable to parse file "vendor/twig/twig/src/Extension/EscaperExtension.php", an error was detected: "" is not a valid Fqsen.
22:02:43 ALERT     [app]   Unable to parse file "vendor/twig/twig/src/Extension/EscaperExtension.php", an error was detected: "" is not a valid Fqsen.
22:02:43 ALERT     [app]   Unable to parse file "vendor/twig/twig/src/Extension/StringLoaderExtension.php", an error was detected: "" is not a valid Fqsen.
22:02:43 ALERT     [app]   Unable to parse file "vendor/twig/twig/src/Extension/StringLoaderExtension.php", an error was detected: "" is not a valid Fqsen.
 4066/6055 [==================>---------]  67%22:03:16 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php", an error was detected: ?array is not a collection
22:03:16 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php", an error was detected: ?array is not a collection
 4072/6055 [==================>---------]  67%
```

If you wish to use my project to experiment with PHPDoc, [here you go](https://gitlab.com/Angius/omnibus).

**Comment by jaapio** [comment] 2020-01-03 07:06
Thanks a lot for the reply.
I will have a look what is going on.

**Comment by jaapio** [comment] 2020-01-03 15:37
about the ignore we can be very clear. phpdoc v2 was doing something there to split the arguments. But since that required custom code for an unclear purpose, we decided to remove the comma-separated behavior. The docs, however, need an update. 

the new command should look like:
`php phpdoc.phar -d ./ -t docs - -ignore node_modules/  --ignore semantic/ --ignore tinymce/ --ignore ./vendor/ --cache-folder ../phpdoc_cache`

note that I removed the dot folders from the ignore since they are ignored by default. 

Having that said, the output tells me that it is trying to parse 65 files. The rendering fails with an error. Which is most likaly an issue in a docblock somewhere in your project. Since phpdoc v3 is more strict about what is allowed. We need to improve the feedback. But what it is telling me now it looks ok. 

```
In class.html.twig line 110:

  An exception has been thrown during the rendering of a template (""\Backend\Models\User::$joined;" is not a valid Fqsen.").
```

**Comment by Atulin** [comment] 2020-01-03 19:24
I tried the new command and, well...

```
E:\Software\Laragon\www\omnibus (dev -> Gitlab) (wwsis@1.0.0)
λ php phpdoc.phar -d ./ -t docs - -ignore node_modules/ --ignore semantic/ --ignore tinymce/ --ignore ./vendor/ --cache-folder ../phpdoc_cache
19:23:11 ERROR     [console] Error thrown while running command "-d "./" -t docs - -ignore "node_modules/" --ignore "semantic/" --ignore "tinymce/" --ignore "./vendor/" --cache-folder "../phpdoc_cache". Message: "Too many arguments, expected arguments "command"." ["exception" => Symfony\Component\Console\Exception\RuntimeException^ { …},"command" => "-d "./" -t docs - -ignore "node_modules/" --ignore "semantic/" --ignore "tinymce/" --ignore "./vendor/" --cache-folder "../phpdoc_cache"","message" => "Too many arguments, expected arguments "command"."]
19:23:11 ERROR     [console] Error thrown while running command "-d "./" -t docs - -ignore "node_modules/" --ignore "semantic/" --ignore "tinymce/" --ignore "./vendor/" --cache-folder "../phpdoc_cache". Message: "Too many arguments, expected arguments "command"." ["exception" => Symfony\Component\Console\Exception\RuntimeException^ { …},"command" => "-d "./" -t docs - -ignore "node_modules/" --ignore "semantic/" --ignore "tinymce/" --ignore "./vendor/" --cache-folder "../phpdoc_cache"","message" => "Too many arguments, expected arguments "command"."]


  Too many arguments, expected arguments "command".


project:run [-t|--target [TARGET]] [--cache-folder [CACHE-FOLDER]] [-f|--filename [FILENAME]] [-d|--directory [DIRECTORY]] [--encoding [ENCODING]] [--extensions [EXTENSIONS]] [-i|--ignore [IGNORE]] [--ignore-tags [IGNORE-TAGS]] [--hidden] [--ignore-symlinks] [-m|--markers [MARKERS]] [--title [TITLE]] [--force] [--validate] [--visibility [VISIBILITY]] [--defaultpackagename [DEFAULTPACKAGENAME]] [--sourcecode] [--template [TEMPLATE]] [--parseprivate] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-c|--config [CONFIG]] [--log [LOG]] [-e|--env ENV] [--no-debug] [--] <command>
```

**Comment by jaapio** [comment] 2020-01-03 19:25
sorry I made a copy past error. 
`php phpdoc.phar -d ./ -t docs --ignore node_modules/ --ignore semantic/ --ignore tinymce/ --ignore ./vendor/ --cache-folder ../phpdoc_cache`

**Comment by Atulin** [comment] 2020-01-03 19:38
So this is odd, seems like vendor is still not ignored.

```
E:\Software\Laragon\www\omnibus (dev -> Gitlab) (wwsis@1.0.0)
λ php phpdoc.phar -d ./ -t docs --ignore node_modules/ --ignore semantic/ --ignore tinymce/ --ignore ./vendor/ --cache-folder ../phpdoc_cache
phpDocumentor 8bbe8ca

Parsing files
 4100/6055 [==================>---------]  67%19:28:46 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php", an error was detected: ?array is not a collection
19:28:46 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php", an error was detected: ?array is not a collection
 4111/6055 [===================>--------]  67%19:29:45 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php", an error was detected: string is not a collection
19:29:45 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php", an error was detected: string is not a collection
 4144/6055 [===================>--------]  68%19:29:53 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/PluginManager/ComposerLock.php", an error was detected: An array can have only integers or strings as keys
19:29:53 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/PluginManager/ComposerLock.php", an error was detected: An array can have only integers or strings as keys
19:29:53 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/PluginManager/PluginList.php", an error was detected: ?array is not a collection
19:29:53 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/PluginManager/PluginList.php", an error was detected: ?array is not a collection
 4161/6055 [===================>--------]  68%19:29:56 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/Provider/FunctionParamsProvider.php", an error was detected: ?array is not a collection
19:29:56 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/Provider/FunctionParamsProvider.php", an error was detected: ?array is not a collection
19:29:57 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/Provider/MethodParamsProvider.php", an error was detected: ?array is not a collection
19:29:57 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/Provider/MethodParamsProvider.php", an error was detected: ?array is not a collection
19:29:57 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/Provider/MethodReturnTypeProvider.php", an error was detected: ?array is not a collection
19:29:57 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/Provider/MethodReturnTypeProvider.php", an error was detected: ?array is not a collection
 4190/6055 [===================>--------]  69%19:30:00 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/Provider/ReturnTypeProvider/PdoStatementSetFetchMode.php", an error was detected: ?array is not a collection
19:30:00 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/Provider/ReturnTypeProvider/PdoStatementSetFetchMode.php", an error was detected: ?array is not a collection
 4199/6055 [===================>--------]  69%19:30:01 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/Scope/IfScope.php", an error was detected: An array can have only integers or strings as keys
19:30:01 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/Scope/IfScope.php", an error was detected: An array can have only integers or strings as keys
 4207/6055 [===================>--------]  69%19:30:01 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/Stubs/Amp.php", an error was detected: A type is missing in an array expression
19:30:01 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/Stubs/Amp.php", an error was detected: A type is missing in an array expression
19:30:02 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/Stubs/CoreGenericClasses.php", an error was detected: An array can have only integers or strings as keys
19:30:02 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/Stubs/CoreGenericClasses.php", an error was detected: An array can have only integers or strings as keys
19:30:02 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/Stubs/CoreGenericFunctions.php", an error was detected: An array can have only integers or strings as keys
19:30:02 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/Stubs/CoreGenericFunctions.php", an error was detected: An array can have only integers or strings as keys
 4220/6055 [===================>--------]  69%19:30:04 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeCombination.php", an error was detected: ?array is not a collection
19:30:04 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeCombination.php", an error was detected: ?array is not a collection
 4442/6055 [====================>-------]  73%19:30:12 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Plugin/Hook/FunctionParamsProviderInterface.php", an error was detected: ?array is not a collection
19:30:12 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Plugin/Hook/FunctionParamsProviderInterface.php", an error was detected: ?array is not a collection
 4463/6055 [====================>-------]  73%19:30:13 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Plugin/Hook/MethodParamsProviderInterface.php", an error was detected: ?array is not a collection
19:30:13 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Plugin/Hook/MethodParamsProviderInterface.php", an error was detected: ?array is not a collection
19:30:13 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Plugin/Hook/MethodReturnTypeProviderInterface.php", an error was detected: ?array is not a collection
19:30:13 ALERT     [app]   Unable to parse file "vendor/vimeo/psalm/src/Psalm/Plugin/Hook/MethodReturnTypeProviderInterface.php", an error was detected: ?array is not a collection
 5352/6055 [========================>---]  88%19:31:40 ALERT     [app]   Unable to parse file "vendor/zetacomponents/base/src/file.php", an error was detected: A type is missing in an array expression
19:31:40 ALERT     [app]   Unable to parse file "vendor/zetacomponents/base/src/file.php", an error was detected: A type is missing in an array expression
```
and rerunning it with `vendor/` instead of `./vendor/` gives me this output:
```
λ php phpdoc.phar -d ./ -t docs --ignore node_modules/ --ignore semantic/ --ignore tinymce/ --ignore vendor/ --cache-folder ../phpdoc_cache
phpDocumentor 8bbe8ca

Parsing files
 65/65 [============================] 100%19:37:55 ERROR     [console] Error thrown while running command "-d "./" -t docs --ignore "node_modules/" --ignore "semantic/" --ignore "tinymce/" --ignore "vendor/" --cache-folder "../phpdoc_cache". Message: "Impossible to create the root directory "file:///E:/Software/Laragon/www/omnibus/docs". mkdir(): No such file or directory" ["exception" => League\Flysystem\Exception^ { …},"command" => "-d "./" -t docs --ignore "node_modules/" --ignore "semantic/" --ignore "tinymce/" --ignore "vendor/" --cache-folder "../phpdoc_cache"","message" => "Impossible to create the root directory "file:///E:/Software/Laragon/www/omnibus/docs". mkdir(): No such file or directory"]
19:37:55 ERROR     [console] Error thrown while running command "-d "./" -t docs --ignore "node_modules/" --ignore "semantic/" --ignore "tinymce/" --ignore "vendor/" --cache-folder "../phpdoc_cache". Message: "Impossible to create the root directory "file:///E:/Software/Laragon/www/omnibus/docs". mkdir(): No such file or directory" ["exception" => League\Flysystem\Exception^ { …},"command" => "-d "./" -t docs --ignore "node_modules/" --ignore "semantic/" --ignore "tinymce/" --ignore "vendor/" --cache-folder "../phpdoc_cache"","message" => "Impossible to create the root directory "file:///E:/Software/Laragon/www/omnibus/docs". mkdir(): No such file or directory"]

In Local.php line 112:

  Impossible to create the root directory "file:///E:/Software/Laragon/www/omnibus/docs". mkdir(): No such file or
  directory


project:run [-t|--target [TARGET]] [--cache-folder [CACHE-FOLDER]] [-f|--filename [FILENAME]] [-d|--directory [DIRECTORY]] [--encoding [ENCODING]] [--extensions [EXTENSIONS]] [-i|--ignore [IGNORE]] [--ignore-tags [IGNORE-TAGS]] [--hidden] [--ignore-symlinks] [-m|--markers [MARKERS]] [--title [TITLE]] [--force] [--validate] [--visibility [VISIBILITY]] [--defaultpackagename [DEFAULTPACKAGENAME]] [--sourcecode] [--template [TEMPLATE]] [--parseprivate] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-c|--config [CONFIG]] [--log [LOG]] [-e|--env ENV] [--no-debug] [--] <command>
```

**Comment by jaapio** [comment] 2020-01-03 19:41
ok, thanks, I see that you are also on windows. 
we have more issues with windows. I will download windows and try it myself

**Comment by jaapio** [comment] 2020-01-04 20:01
Just to be sure, your project is not on a network drive is it?

Having issues right now on windows using a mounted directory from my linux machine.

**Comment by jaapio** [comment] 2020-01-04 20:28
I was able to reproduce the issue you have on a windows machine. 
Thanks for your feedback. I think we can address this. Please follow #2130 for more updates. Since this is literally the same issue.

**Closed by jaapio** 2020-01-04 20:28 UTC
Labels: bug, needs author update
