### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by Kabingeran** [phpDocumentor/phpDocumentor#3377] opened 2022-11-21 21:43 UTC
## Expected behavior
Help command output

## Actual behavior
PHP Deprecated:  Return type of HumbugBox380\KevinGH\RequirementChecker\RequirementCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/phpDocumentor/.box/src/RequirementCollection.php on line 15

Deprecated: Return type of HumbugBox380\KevinGH\RequirementChecker\RequirementCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/phpDocumentor/.box/src/RequirementCollection.php on line 15
PHP Deprecated:  Return type of HumbugBox380\KevinGH\RequirementChecker\RequirementCollection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/phpDocumentor/.box/src/RequirementCollection.php on line 19

Deprecated: Return type of HumbugBox380\KevinGH\RequirementChecker\RequirementCollection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/phpDocumentor/.box/src/RequirementCollection.php on line 19
PHP Fatal error:  Cannot declare interface Psr\EventDispatcher\EventDispatcherInterface, because the name is already in use in phar:///usr/local/bin/phpDocumentor/vendor/psr/event-dispatcher/src/EventDispatcherInterface.php on line 9

Fatal error: Cannot declare interface Psr\EventDispatcher\EventDispatcherInterface, because the name is already in use in phar:///usr/local/bin/phpDocumentor/vendor/psr/event-dispatcher/src/EventDispatcherInterface.php on line 9

## Steps to reproduce the problem

1. Install
2. Run

## Your environment

Version used: 3.3.1
Install method: Stand-alone, downloading a PHAR
PHP version: 8.1.9
Operating system and version (e.g. Ubuntu 20.04, Windows 10): Alpine 3.16
Attach code that is involved (install): wget -qcO /usr/local/bin/phpdoc https://github.com/phpDocumentor/phpDocumentor/releases/download/v3.3.1/phpDocumentor.phar && chmod +x /usr/local/bin/phpdoc

**Comment by mvriel** [comment] 2022-12-04 08:04
I have tried to reproduce the issue by starting an official PHP Docker container using 8.1.9 and Alpine:

```
docker run --rm -it php:8.1.9-alpine /bin/sh
```

And then running your example:

```
curl -sSLo /usr/local/bin/phpDocumentor https://github.com/phpDocumentor/phpDocumentor/releases/download/v3.3.1/phpDocumentor.phar && chmod +x /usr/local/bin/phpDocumentor
```

When I run phpDocumentor without arguments or with the `--help` argument, I see the deprecation messages that you include as well, but I do not get that fatal error. This gives me the idea that there is another variable at play why you run into this issue. 

1. If you run the above commands, do you still get the error? 
2. And if so: what is different, do you have a specific codebase on which this errors when you try to use phpDocumentor? 
3. Does it run when you have a simple PHP file with one class in it?

I am trying to reproduce the issue but am not having much luck so far

**Comment by Kabingeran** [comment] 2022-12-04 10:45
To be honest, I haven't explored the issue in depth. Here is some information:
https://nimb.ws/JbnaY7

**Comment by mvriel** [comment] 2022-12-04 17:35
Hmm, there is nothing I can see there that would explain the behaviour.. I would need to try and reproduce your scenario with a clean project that has the EventDispatcher as dependency. Perhaps it has something to do with that?

**Comment by Kabingeran** [comment] 2022-12-05 06:30
I think it's all about the pecl extension psr. You need to make sure they don't conflict.

**Comment by mvriel** [comment] 2022-12-05 06:40
I am super grateful for this addition. I was unaware there is a PECL extension for the PSRs, and this explains a lot :) It has been some time ago since I have had to change anything about the PHAR compilation process, but I seem to remember that we use a library that changes namespaces during the building process, we probably need to tweak that to include these

**Comment by mvriel** [comment] 2022-12-07 06:36
Hmm, I don't see phpscoper used currently. I have reached out to @jaapio to check if we scope the dependencies some other way. Otherwise it may be interesting to introduce phpscoper in our phar building process, though that is not a small feat

**Comment by mvriel** [comment] 2022-12-08 17:37
I tried getting php-scoper into the phar building process but I need to dive into how it's build. It seems we no longer use the make command but instead the phar-ga github action. 

@jaapio do you know how this works? Also, we may want to upgrade box to 3.16 (latest that still works with php 7.4). I think php-scoper doesn't work in box with the current version

**Comment by jamesjohnmcguire** [comment] 2023-01-02 13:00
I'm not getting a fatal error, but I'm getting a lot (20+?) of these deprecation warnings.  Will these be taken care of, in association with this issue, or should another issue be opened up?

**Comment by mvriel** [comment] 2023-03-24 07:40
As for the deprecations, these are upstream issues as far as I can determine right now. When we were to upgrade box, they may be resolved but at the moment our focus is not yet on these deprecation messages.

**Comment by jaapio** [comment] 2023-07-19 20:13
This will be fixed in the next release. Thanks for reporting.

**Closed by jaapio** 2023-07-19 20:13 UTC
Labels: bug
