### ISSUE TITLE
Error: Object of class phpDocumentor\Descriptor\Collection could not be converted to string 

### ISSUE THREAD

**Issue by okou19900722** [phpDocumentor/phpDocumentor#2125] opened 2019-08-28 07:38 UTC
hi, It's not same like #992, it's happend in CoreExtension.php.

```
PHP Warning:  Uncaught ErrorException: Catchable Fatal Error: Object of class phpDocumentor\Descriptor\Collection could not be converted to string in phar://H:/okou/workspace/idea/phpdoc-test/phpdoc.phar/vendor/twig
/twig/src/Extension/CoreExtension.php:760
Stack trace:
#0 H:\okou\workspace\idea\phpdoc-test\target\phpdoc\twig\e7\e7b63af1999db994e78bbdcd94c45953f2fe9a686e0c5a73be459a5952be63f8.php(95): twig_join_filter(Array, ', ')
#1 phar://H:/okou/workspace/idea/phpdoc-test/phpdoc.phar/vendor/twig/twig/src/Template.php(216): __TwigTemplate_62d7bb51142230bda849e4de1623483fa616450099dcc221d080e98df9921f7a->block_content(Array, Array)
#2 H:\okou\workspace\idea\phpdoc-test\target\phpdoc\twig\dc\dcd974ced9fda1b518eadf4d34e99632b05445194107ff544e2b0231694eaf7a.php(89): Twig\Template->displayBlock('content', Array, Array)
#3 phar://H:/okou/workspace/idea/phpdoc-test/phpdoc.phar/vendor/twig/twig/src/Template.php(443): __TwigTemplate_8f201f77bfc075538f9bbc0a1ed3de9c1eb36ac1eb3979093a66b285e011aaec->doDisplay(Array, Array)
#4 phar:/ in phar://H:/okou/workspace/idea/phpdoc-test/phpdoc.phar/vendor/twig/twig/src/Extension/CoreExtension.php on line 760
PHP Fatal error:  Object of class phpDocumentor\Descriptor\Collection could not be converted to string in phar://H:/okou/workspace/idea/phpdoc-test/phpdoc.phar/vendor/twig/twig/src/Extension/CoreExtension.php on lin
e 760
[2019-08-28 07:25:46] php.CRITICAL: Fatal Error: Object of class phpDocumentor\Descriptor\Collection could not be converted to string {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException
(code: 0): Error: Object of class phpDocumentor\\Descriptor\\Collection could not be converted to string at phar://H:/okou/workspace/idea/phpdoc-test/phpdoc.phar/vendor/twig/twig/src/Extension/CoreExtension.php:760)
"} []
[2019-08-28 07:25:46] php.CRITICAL: Fatal Error: Object of class phpDocumentor\Descriptor\Collection could not be converted to string {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException
(code: 0): Error: Object of class phpDocumentor\\Descriptor\\Collection could not be converted to string at phar://H:/okou/workspace/idea/phpdoc-test/phpdoc.phar/vendor/twig/twig/src/Extension/CoreExtension.php:760)
"} []

In CoreExtension.php line 760:
                                                                                               
  Error: Object of class phpDocumentor\Descriptor\Collection could not be converted to string 
```

**Comment by jaapio** [comment] 2019-09-02 17:59
Please specify your phpdoc version. Otherwise we won't be able to fix this issue.

**Comment by okou19900722** [comment] 2019-09-03 00:29
the version is `v3.0.0-alpha.4`

**Comment by mvriel** [comment] 2019-12-14 19:23
Are you able to verify whether the issue is still there with the PHAR at https://github.com/phpDocumentor/phpDocumentor/suites/358520704/artifacts/693056? We have been making significant improvements in type strictness.

If the issue is not resolved; can you tell me which codebase you use or have an example + which template you use? CoreExtension is by Twig itself and based on my code here I cannot deduce which Twig template and/or part of a Twig template causes the issue that you show.

**Comment by jaapio** [comment] 2020-10-13 20:18
Closing because this issue is rather old. A lot has been changed in between. Feel free to open a new issue when you are facing issues with the latest build.

**Closed by jaapio** 2020-10-13 20:18 UTC
Labels: needs author update
