### ISSUE TITLE
source code: Error 404 while fetching file: Not Found

### ISSUE THREAD

**Issue by aqua-calc** [phpDocumentor/phpDocumentor#1461] opened 2014-10-31 01:44 UTC
Hello,

I've just updated to 2.8.0 and getting the following problem while trying to access the files sourcode.

&lt;div class="modal-body"&gt;
        &lt;pre data-src="../files/inc/class_aq_pdo.inc.php.txt" class="language-php line-numbers">&lt;/pre&gt;
&lt;/div&gt;

However, the actual file name is "files/inc%2Fclass_aq_pdo.inc.php.txt" -- there's no "files/inc/" folder generated.

Thank you.

**Comment by DaveWP** [comment] 2015-01-24 16:37
Recommend, the implementation is surrounded by a check for the operating system.  i.e. The corrected code should be:

                if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
                    $filepart = urlencode(iconv('UTF-8', 'ASCII//TRANSLIT', $filepart));
                }

**Comment by mvriel** [comment] 2015-02-18 20:43
I think this is actually a duplicate of #1390 but I will add both to 2.8.2 to make sure it is solved

**Comment by danchivz** [comment] 2015-04-04 01:02
Version 2.8.2, still not solved. For example, `data-src` is now `data-src="../files/Captcha\AbstractWord.php.txt"`. Since backslash is unsafe character in url, it is sent as `../files/Captcha%5CAbstractWord.php.txt` by Firefox, but interesting, Chrome replaces backslash to forward slash and sends the right request. A quick solution is to change the first line in `loadExternalCodeSnippets()` function in twig templates to `var src = pre.getAttribute('data-src').replace( /\\/g, '/' );`

**Comment by jaapio** [comment] 2021-06-04 15:48
fixed in phpdoc v3. https://github.com/phpDocumentor/phpDocumentor/pull/2919

**Closed by jaapio** 2021-06-04 15:48 UTC
Labels: Up-for-grabs, bug, help wanted
