### ISSUE TITLE
Erros when updated PHP to 8.0.3

### ISSUE THREAD

**Issue by AllanAndrade** [phpDocumentor/phpDocumentor#2880] opened 2021-04-27 23:52 UTC
On folder that contains just the file: phpDocumentor.phar 

**When run:**
$php phpDocumentor.phar 

**I've got:**                                                                                                        
 [WARNING] Some commands could not be registered:                                                                       
In Filter_6ae6af3.php line 5:
  Call to undefined function ContainerLx0j6hQ\include_once\dirname()  
  There are no commands defined in the "project" namespace.  
                                                             
**My system:**
* Version used: Latest downloaded today.
* Install method: manual (just downloaded the file)
* PHP version: 8.0.3
* Operating system and version: Ubuntu 20.04.2 LTS

**Comment by Txxkirsch** [comment] 2021-05-06 20:21
Same here.
Tried via phive-installation: php tools/phpDocumentor and PHAR-File.
Docker-Image couldn't be used because its not for ARM-architecture

```
php -v
PHP 8.0.5 (cli) (built: May  3 2021 11:58:58) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.5, Copyright (c), by Zend Technologies
    with Xdebug v3.0.3, Copyright (c) 2002-2021, by Derick Rethans
```
Running on Raspi4

```
uname -a
Linux rasp4blite 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux
```

**Comment by Blaztix** [comment] 2021-05-11 03:35
>= php8.0 is not support yet

**Comment by NicolasCARPi** [comment] 2021-05-12 14:46
@Blaztix thanks for the workaround, I can confirm it works.

**Comment by jaapio** [comment] 2021-06-04 17:43
I will close this issue since our nightly builds do support php8. But we didn't create a release for this yet.

**Closed by jaapio** 2021-06-04 17:43 UTC
