### ISSUE TITLE
3.0.0-RC: 'OC*' is not recognized ...

### ISSUE THREAD

**Issue by jrfnl** [phpDocumentor/phpDocumentor#2291] opened 2020-02-14 21:37 UTC
Test run on PHPCSUtils using PHP 7.4.2 with PHPDocumentor 3.0.0-RC (phar) on Windows 7 yields the following output:

```
# phpdoc3
PHP 7.4.2 (cli) (built: Jan 21 2020 17:53:48) ( ZTS Visual C++ 2017 x86 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

phpDocumentor v3.0.0-rc

Parsing files
 25/25 [============================] 100%
Applying transformations (can take a while)
 16/16 [============================] 100%
All done in 42 seconds!
'OC*' is not recognized as an internal or external command,
operable program or batch file.

Exit code is 9009
```

## Expected Behavior
Exit code `0` and no error `'OC*' is not recognized as an internal or external command, operable program or batch file.` at the end of the run.

## Actual Behavior
See above.

## Steps to Reproduce the Problem

  1. Check out the following branch: https://github.com/PHPCSStandards/PHPCSUtils/tree/WIP/set-up-phpdocumentor
  2. Run phpdoc from the phar without additional parameters.

## Your environment

* Version used: 3.0.0-RC
* Install method: Phar called via a `.bat` file
* php version: 7.4.2
* Operating system and version: Windows 7
* Link to your project: https://github.com/PHPCSStandards/PHPCSUtils

**Comment by jrfnl** [comment] 2020-02-14 22:07
Looks like this only happens on a first run. I can't seem to reproduce it anymore on subsequent runs... 

Feel free to close the issue if you think it is a fluke.

**Comment by ashnazg** [comment] 2020-02-14 22:15
That might indicate that regular execution assumes some environmental piece pre-exists (e.g. cache).  I guess it's not painful if it's clear upon a second run, but might be a good UX bug to squash if I'm right.

**Comment by mvriel** [comment] 2020-02-15 07:10
That you cannot reproduce it on subsequent runs may be due to the caching mechanism that we use. After parsing we store the parsed results and on subsequent runs we check whether the file's contents have changed and re-parse only those files that have changed.

If you add `--force` to the command, then the issue could be reproducible. 

I have searched in our code where I could find `OC*` or something related but nothing popped up. I am really interested in why this happens because this is something I did not expect.

**Comment by jrfnl** [comment] 2020-02-15 07:14
I've just tried with `--force` and weirdly enough, still cannot reproduce the issue:
```
# phpdoc3 --force
PHP 7.4.2 (cli) (built: Jan 21 2020 17:53:48) ( ZTS Visual C++ 2017 x86 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

phpDocumentor v3.0.0-rc

Parsing files
 25/25 [============================] 100%
Applying transformations (can take a while)
 16/16 [============================] 100%
All done in 50 seconds!

Exit code is 0
```

**Comment by mvriel** [comment] 2020-02-15 07:24
That is confusing :) Also: only know I noticed that the error occurs at the end of the whole process and that undermines my theory that it happens during parsing.

I am afraid that I would have to close this issue indeed; but if it occurs again. Please let us know because I would feel awkward if phpDocumentor would inadvertently execute things it should not

**Closed** 2020-02-15 07:25 UTC

**Comment by jrfnl** [comment] 2020-02-15 07:27
Will do and at least there is a record of this occurring now, so hopefully if someone else comes across it they will add to this issue.

**Comment by jrfnl** [comment] 2020-02-15 07:34
Just for arguments sake, I've run one more test. Physically throwing all previously generated files away before running the command and still cannot reproduce.

**Comment by mvriel** [comment] 2020-02-15 07:34
Thanks for being so thorough :)

**Comment by jrfnl** [comment] 2020-02-15 07:39
@mvriel For you: always ;-)
