### ISSUE TITLE
Deprecated: Creation of dynamic property

### ISSUE THREAD

**Issue by winstrand** [phpDocumentor/phpDocumentor#3711] opened 2024-05-05 14:31 UTC
Got following when running from command line:
Deprecated: Creation of dynamic property PhpParser\Node\Stmt\PropertyProperty::$fqsen ...
Deprecated: Creation of dynamic property PhpParser\Node\Stmt\ClassMethod::$fqsen ... 
Deprecated: Creation of dynamic property PhpParser\Node\Stmt\Namespace_::$fqsen ...
Deprecated: Creation of dynamic property PhpParser\Node\Stmt\Class_::$fqsen ...

The documentation is generated, but there is a ton of PHP warning messages printed during execution.

## Expected behavior
No deprecation warnings

## Steps to reproduce the problem

1. Windwos command Line: php %phpDocumentorPATH%\phpDocumentor.phar

## Your environment
phpdoc --version
phpDocumentor vv3.4.3
installed with wget 

Enviroment:
php -v
PHP 8.2.12 (cli) (built: Oct 24 2023 21:15:15) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.12, Copyright (c) Zend Technologies

Installd with XAMPP

OS: Windows 11 (22H2)

**Comment by jaapio** [comment] 2024-05-05 20:00
Duplicate of https://github.com/phpDocumentor/Reflection/issues/529

Will be solved in the next release

**Closed** 2024-05-05 20:00 UTC
