### ISSUE TITLE
Expected an instance of phpDocumentor\Reflection\Php\File. Got: phpDocumentor\Reflection\Php\Method

### ISSUE THREAD

**Issue by brainfork** [phpDocumentor/phpDocumentor#3310] opened 2022-08-12 00:02 UTC
## Expected behavior

Running `phpdoc` with the [basic config file](https://docs.phpdoc.org/3.0/guide/references/configuration.html) should generate documentation somewhere in the working directory

## Actual behavior

Running `phpdoc` with the basic config file results in this output in the console:
```
$ phpdoc
phpDocumentor v3.3.1

Parsing files
  1/28 [=>--------------------------]   3%23:43:58 ALERT     [app]   Unable to parse file "admin/class-plugin-admin.php", an error was detected: Expected an instance of phpDocumentor\Reflection\Php\File. Got: phpDocumentor\Reflection\Php\Method
 28/28 [============================] 100%
Applying transformations (can take a while)
 21/21 [============================] 100%
All done in 2 seconds!
```
and the creation of a `.phpdoc\cache` folder containing a bunch of gibberish files in the working directory

## Steps to reproduce the problem

1. Run phpdoc command in root directory of a project
2.
3.

## Your environment

* Version used: 3.3.1
* Install method: .phar
* PHP version: 7.4.26
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): Windows 10
* Link to your project: https://github.com/FlowPress/plugin-fph-plugin (private repo, doesn't have phpDocumentor implemented as I'm still testing locally)
* Attach code that is involved: attached
* ...
[fph-plugin.zip](https://github.com/phpDocumentor/phpDocumentor/files/9312765/fph-plugin.zip)

**Comment by brainfork** [comment] 2022-08-12 00:06
For reference, here's the verbose output:
```
$ phpdoc -vvvv
phpDocumentor v3.3.1

23:32:43 NOTICE    [app] Using the configuration file at the default location
23:32:43 INFO      [app] Logging to: .phpdoc/cache
23:32:43 INFO      [app] Checking whether to purge cache
23:32:43 INFO      [app] Collecting files from .
23:32:44 INFO      [app] OK
23:32:44 INFO      [app] Loading project from cache
23:32:44 NOTICE    [app] Parsing files
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+22,528 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 DEBUG     [app] >> Memory after processing of file: 22.00 megabytes (+0 kilobytes)
23:32:44 INFO      [app] Elapsed time to parse all files: 0.03s
23:32:44 INFO      [app] Peak memory usage: 22M
23:32:44 NOTICE    [app] Storing cache ..
23:32:44 INFO      [app] OK
23:32:44 INFO      [app] Loading project from cache
23:32:44 DEBUG     [app] In the ProjectDescriptor are:
        28 files
         1 top-level namespaces
         0 unresolvable parent classes
         4 phpDocumentor\Descriptor\ConstantDescriptor elements
         3 phpDocumentor\Descriptor\FunctionDescriptor elements
        16 phpDocumentor\Descriptor\ClassDescriptor elements
        80 phpDocumentor\Descriptor\MethodDescriptor elements
        27 phpDocumentor\Descriptor\PropertyDescriptor elements
         2 phpDocumentor\Descriptor\NamespaceDescriptor elements

23:32:44 INFO      [app]
Applying 21 transformations
23:32:44 NOTICE    [app]   Writer twig  on index.html
23:32:44 NOTICE    [app]   Writer twig  using query "files" on
23:32:44 NOTICE    [app]   Writer sourcecode  using query "files" on files/{{path}}.txt
23:32:44 NOTICE    [app]   Writer twig  using query "indexes.namespaces" on
23:32:44 NOTICE    [app]   Writer twig  using query "indexes.packages" on
23:32:45 NOTICE    [app]   Writer twig  using query "indexes.classes" on
23:32:45 NOTICE    [app]   Writer twig  using query "indexes.enums" on
23:32:45 NOTICE    [app]   Writer twig  using query "indexes.interfaces" on
23:32:45 NOTICE    [app]   Writer twig  using query "indexes.traits" on
23:32:45 NOTICE    [app]   Writer twig  on js/search.js
23:32:45 NOTICE    [app]   Writer twig  on js/searchIndex.js
23:32:45 NOTICE    [app]   Writer twig  on graphs/classes.html
23:32:45 NOTICE    [app]   Writer twig  on reports/errors.html
23:32:45 NOTICE    [app]   Writer twig  on reports/deprecated.html
23:32:45 NOTICE    [app]   Writer twig  on reports/markers.html
23:32:45 NOTICE    [app]   Writer twig  on indices/files.html
23:32:45 NOTICE    [app]   Writer twig  on css/base.css
23:32:45 NOTICE    [app]   Writer twig  on css/normalize.css
23:32:45 NOTICE    [app]   Writer twig  on css/template.css
23:32:45 NOTICE    [app]   Writer RenderGuide  on
23:32:45 NOTICE    [app]   Writer Graph  on graphs/classes.svg
23:32:45 NOTICE    [app] Finished transformation process

All done in 2 seconds!
```

**Comment by 4levels** [comment] 2023-07-06 06:46
I ran into the same error message on a large legacy PHP 5.6 project and it was almost impossible to debug.  I ended up temporary removing lines from the particular files until the error went away.  In my case, it turned out there were function declarations inside class functions.  Although being technically possible, having function declarations inside functions can cause all kind of unexpected side-effects and even throw fatal errors if the function is ran more than once.
Once I refactored the code to not have any more nested function declarations, the error stopped occurring and the documentation is now generated correctly.

**Comment by gaxweb** [comment] 2023-07-26 11:45
Can confirm that having something like this:

```
if(!function_exists('apcu_exists')){
	function apcu_exists($key){ return my_apcu_fetch($key); }
}
```

in a file causes the issue to arise.

**Comment by jaapio** [comment] 2023-10-04 20:17
Thanks for your reports, 

I found the cause of this issue and it will be fixed in our next release. If you install phpDocumentor with composer or docker the fix will be available directly as the actual fix is done in an upstream library. `phpdocumentor/reflection`.

**Closed by jaapio** 2023-10-04 20:17 UTC
Labels: bug, research
