### ISSUE TITLE
Type error in Reflection\Php\Method::getHasReturnByReference() using +3.3

### ISSUE THREAD

**Issue by denydias** [phpDocumentor/phpDocumentor#3202] opened 2022-04-03 21:04 UTC
## Expected behavior
Code documentation generated successfully as it happens with 3.2 and lower.

## Actual behavior
When running phpDocumentor with 3.3.1 (happens with 3.3.0 too), I get the following message as output:

```shell
$ phpDocumentor.phar -v
phpDocumentor v3.3.1

20:55:16 NOTICE    [app] Using the configuration file at the default location
20:55:16 NOTICE    [app] Parsing files
20:55:16 CRITICAL  [console] Error thrown while running command "-v". Message: "phpDocumentor\Reflection\Php\Method::getHasReturnByReference(): Return value must be of type bool, null returned" ["exception" => TypeError { …},"command" => "-v","message" => "phpDocumentor\Reflection\Php\Method::getHasReturnByReference(): Return value must be of type bool, null returned"]

In Method.php line 210:
                                                                                                                    
  [TypeError]                                                                                                       
  phpDocumentor\Reflection\Php\Method::getHasReturnByReference(): Return value must be of type bool, null returned  
                                                                                                                    
Exception trace:
at phar:///opt/bin/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Method.php:210
  phpDocumentor\Reflection\Php\Method->getHasReturnByReference() at phar:///opt/bin/phpDocumentor.phar/src/phpDocumentor/Descriptor/Builder/Reflector/MethodAssembler.php:86
  phpDocumentor\Descriptor\Builder\Reflector\MethodAssembler->mapReflectorToDescriptor() at phar:///opt/bin/phpDocumentor.phar/src/phpDocumentor/Descriptor/Builder/Reflector/MethodAssembler.php:64
  phpDocumentor\Descriptor\Builder\Reflector\MethodAssembler->create() at phar:///opt/bin/phpDocumentor.phar/src/phpDocumentor/Descriptor/ProjectDescriptorBuilder.php:103
  phpDocumentor\Descriptor\ProjectDescriptorBuilder->buildDescriptor() at phar:///opt/bin/phpDocumentor.phar/src/phpDocumentor/Descriptor/Builder/Reflector/ClassAssembler.php:119
  phpDocumentor\Descriptor\Builder\Reflector\ClassAssembler->addMethods() at phar:///opt/bin/phpDocumentor.phar/src/phpDocumentor/Descriptor/Builder/Reflector/ClassAssembler.php:69
  phpDocumentor\Descriptor\Builder\Reflector\ClassAssembler->create() at phar:///opt/bin/phpDocumentor.phar/src/phpDocumentor/Descriptor/ProjectDescriptorBuilder.php:103
  phpDocumentor\Descriptor\ProjectDescriptorBuilder->buildDescriptor() at phar:///opt/bin/phpDocumentor.phar/src/phpDocumentor/Descriptor/Builder/Reflector/FileAssembler.php:137
  phpDocumentor\Descriptor\Builder\Reflector\FileAssembler->addClasses() at phar:///opt/bin/phpDocumentor.phar/src/phpDocumentor/Descriptor/Builder/Reflector/FileAssembler.php:69
  phpDocumentor\Descriptor\Builder\Reflector\FileAssembler->create() at phar:///opt/bin/phpDocumentor.phar/src/phpDocumentor/Descriptor/ProjectDescriptorBuilder.php:103
  phpDocumentor\Descriptor\ProjectDescriptorBuilder->buildDescriptor() at phar:///opt/bin/phpDocumentor.phar/src/phpDocumentor/Descriptor/ProjectDescriptorBuilder.php:176
  phpDocumentor\Descriptor\ProjectDescriptorBuilder->createApiDocumentationSet() at phar:///opt/bin/phpDocumentor.phar/src/phpDocumentor/Pipeline/Stage/Parser/ParseFiles.php:63
  phpDocumentor\Pipeline\Stage\Parser\ParseFiles->__invoke() at phar:///opt/bin/phpDocumentor.phar/vendor/league/pipeline/src/FingersCrossedProcessor.php:11
  League\Pipeline\FingersCrossedProcessor->process() at phar:///opt/bin/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php:34
  League\Pipeline\Pipeline->process() at phar:///opt/bin/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php:39
  League\Pipeline\Pipeline->__invoke() at phar:///opt/bin/phpDocumentor.phar/vendor/league/pipeline/src/FingersCrossedProcessor.php:11
  League\Pipeline\FingersCrossedProcessor->process() at phar:///opt/bin/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php:34
  League\Pipeline\Pipeline->process() at phar:///opt/bin/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php:39
  League\Pipeline\Pipeline->__invoke() at phar:///opt/bin/phpDocumentor.phar/src/phpDocumentor/Console/Command/Project/RunCommand.php:290
  phpDocumentor\Console\Command\Project\RunCommand->execute() at phar:///opt/bin/phpDocumentor.phar/vendor/symfony/console/Command/Command.php:298
  Symfony\Component\Console\Command\Command->run() at phar:///opt/bin/phpDocumentor.phar/vendor/symfony/console/Application.php:1033
  Symfony\Component\Console\Application->doRunCommand() at phar:///opt/bin/phpDocumentor.phar/vendor/symfony/framework-bundle/Console/Application.php:96
  Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at phar:///opt/bin/phpDocumentor.phar/vendor/symfony/console/Application.php:299
  Symfony\Component\Console\Application->doRun() at phar:///opt/bin/phpDocumentor.phar/vendor/symfony/framework-bundle/Console/Application.php:82
  Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at phar:///opt/bin/phpDocumentor.phar/vendor/symfony/console/Application.php:171
  Symfony\Component\Console\Application->run() at phar:///opt/bin/phpDocumentor.phar/bin/phpdoc:43
  require() at /opt/bin/phpDocumentor.phar:14
```

## Steps to reproduce the problem

1. Download `phpDocumentor.phar` 3.30 and up, make it executable.
2. Run it against your code base.
3. Bang!

## Your environment

* Version used: 3.3.1
* Install method: as prescribed in `Getting started using the PHAR` on website home.
* PHP version: 8.1.4
* Operating system and version: Slackware 15.1 -current
* Link to your project: private repository, no link available.
* Attach code that is involved: can't get it related to any of my code.
* phpdoc.xml:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor
    configVersion="3"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://www.phpdoc.org"
    xsi:noNamespaceSchemaLocation="https://docs.phpdoc.org/latest/phpdoc.xsd"
>
    <title>MyApp</title>
    <paths>
        <output>documentation/api/</output>
    </paths>
    <version number="0.0.1-dev">
        <api>
            <source dsn=".">
                <path>app/</path>
            </source>
            <extensions>
                <extension>php</extension>
            </extensions>
            <default-package-name>MyApp</default-package-name>
        </api>
    </version>
    <template name="default"/>
</phpdocumentor>
```

**Comment by mvriel** [comment] 2022-07-22 20:33
I'm afraid I haven't been able to reproduce the issue by running that phar file (https://github.com/phpDocumentor/phpDocumentor/releases/download/v3.3.1/phpDocumentor.phar) against the phpDocumentor codebase. 

Reading through the code I am also slightly confused how this can happen. It _might_ be cache related and I recommend clearing your phpdoc cache folder and trying again.

If that doesn't work, can you create a small reproduction codebase / file that I can test with?

**Comment by MLIMG** [comment] 2022-07-22 20:54
Had the same.. clear cache and output directory. solve it for me.

**Comment by mvriel** [comment] 2022-07-23 06:24
It probably has to do with serializing classes with untyped properties but typed method signatures. What can happen is that the property has a null value because it is newly introduced and thus not included in the previous serialization and the method invocations will break on this.

Aside from that we quite recently bumped our minimum PHP version to 7.4 and still need to go through our codebase to apply types to properties (and setting proper default values), there is little we can do about it in the short run.

The only thing that is slightly off here is that we have a mechanism that detects whether you use a newer version of phpDocumentor and it should force a rebuild of the cache the first time you run it. But I do not remember whether this is only regarding the config cache or also about the parser cache.

In any case, I am going to close this issue as it strongly looks like a cache issue.

**Closed by mvriel** 2022-07-23 06:24 UTC
Labels: research, needs author update

**Comment by denydias** [comment] 2022-07-29 12:00
> It _might_ be cache related and I recommend clearing your phpdoc cache folder and trying again.

I also confirm clearing cache did the trick.

Now I hit #3290 but that's another story, fortunately with a merged PR so it's just a matter to wait for a new release.

Thanks for the reply and the awesome work, @mvriel.
