### ISSUE TITLE
@see tag doesn't link to FQSEN classname::header()

### ISSUE THREAD

**Issue by mmeciar** [phpDocumentor/phpDocumentor#3070] opened 2021-11-19 22:38 UTC
In my class comment Im using tag 
@see classname::header()

Generated documentation doesn't create html link to FQSEN if method name is **header()**.

Inline tag doesn't work eiter.

phpDocumentor v3.1.2

**Comment by mvriel** [comment] 2022-07-23 20:39
I have tried to reproduce this issue on the latest version of phpDocumentor and it seems to be resolved already. Unless I misunderstand the description above.

I have added a method called `header` to the VersionSpecification class; and the `@see` tag that you mention and I get the following output:
![image](https://user-images.githubusercontent.com/193704/180622052-6fcfeff8-a6cf-4e43-b4cd-8601f3f8db17.png)

And this is the code I used.

```
/**
 * @see VersionSpecification::header()
 */
class VersionSpecification
{
```

As I believe the issue is already resolved in a newer version of phpDocumentor I am going to close this issue. If I made a mistake in my reproduction scenario or you still experience the issue; please provide a more detailed reproduction case so that I can test against that.

**Closed by mvriel** 2022-07-23 20:39 UTC
