### ISSUE TITLE
Latest alpha is failing to even parse

### ISSUE THREAD

**Issue by auroraeosrose** [phpDocumentor/phpDocumentor#2011] opened 2018-08-21 18:19 UTC
Latest alpha doesn't run and outputs strange errors on windows

## Expected Behavior
Documentation generated
This works with a version 2 phar with an identical command, however the output is useless because of #1914 mucking up all the documentation generated with errors

## Actual Behavior
Nothing but a strange output error

## Steps to Reproduce the Problem

  1. php "C:\xxx\docs\phpDocumentor.phar" -d "C:\xxxx\src" -t "C:\xxx\api"

Output
 There are no commands defined in the "C" namespace.

## Your environment
Version: v3.0.0-alpha.2-nightly-gdff5545
Phar
PHP 7.2.8
Windows 10

**Comment by ashnazg** [comment] 2018-08-22 18:07
What happens if you add the `run` command to it:

`php "C:\xxx\docs\phpDocumentor.phar" run -d "C:\xxxx\src" -t "C:\xxx\api"`

**Comment by auroraeosrose** [comment] 2018-08-24 16:51
In Uri.php line 89:
 file://file://C:\Users\xxx/phpdoc.dist.xml is not  a valid uri 

Command "run" is not defined.  
Did you mean this?             
cache:pool:prune

**Comment by mvriel** [comment] 2018-09-23 14:14
Hi Elizabeth,

I have just done some rework on the configuration but I am not convinced whether that will solve your issue since it may involve windows paths being interpreted differently than on Mac/Linux. I'll need to grab a windows machine to reproduce this behaviour.

As for the message

> There are no commands defined in the "C" namespace.

It would seem that our workaround to have a 'default' Command for Symfony Console has broken. This I will be investigating first and in the mean time find a windows machine :D

Thanks for your patience

**Comment by mvriel** [comment] 2018-09-23 14:55
In the latest version on develop I have fixed that when no recognizable command was passed; it will default to the run command _including_ options and arguments.

Or in other words: executing `php "C:\xxx\docs\phpDocumentor.phar" -d "C:\xxxx\src" -t "C:\xxx\api"` should no longer result in a message saying `There are no commands defined in the "C" namespace.`.

As mentioned earlier, I do not know (yet) whether the error `file://file://C:\Users\xxx/phpdoc.dist.xml is not a valid uri` is fixed yet. On MacOSX this issue doesn't occur, but I'd need to check windows

**Comment by auroraeosrose** [comment] 2018-09-24 14:43
I'm more than happy to test stuff on windows if you need it :)  Just poke me

I can tell you that the current stuff you're using here https://github.com/phpDocumentor/phpDocumentor2/blob/269c74ffd7ba9b4a0f87973141a3af17853bc5b8/src/phpDocumentor/DomainModel/Uri.php#L82 to validate stream paths as a url is going to break all over the place on windows.  There are also several other PHP streams uri schemas that are going to break with this code

There are two functions you're using and some assumptions you're making in the code that will break it

First of all parse_url - as the note says in the manual

    Note:

    This function is intended specifically for the purpose of parsing URLs and not URIs. However, to comply with PHP's backwards compatibility requirements it makes an exception for the file:// scheme where triple slashes (file:///...) are allowed. For any other scheme this is invalid.

That means if you parse a path WITHOUT the file:/// on it it will parse as a url always.  That means if it has backslashes and no file:// prefix... it won't parse correctly.  You can probably fake it by string replacing backslashes, but I'd argue you're simply using the wrong tool.

The second issue is filter_var  with the url flag

filter_var and the FILTER_VALIDATE_URL parses according to http://www.faqs.org/rfcs/rfc2396, but PHP's stream syntax is NOT compliant :)  Neither is Windows path syntax (hurray?)

So frankly you're going to have to rewrite that code to NOT use the filter_var on that path and do something else to verify it.  It might be worth it to write a PHP stream filter validator and parser instead.

Thanks!

**Comment by jaapio** [comment] 2018-10-20 19:37
Hi

I think a number of changes should have fixed this issue. How ever I'm not sure because I don't have a windows box available for testing. 
If you are able to check if this issue is working now correctly I would appreciate that very much. 

Thanks!

**Comment by mvriel** [comment] 2019-12-22 19:43
Our build pipeline now continuously checks against Windows issues; we haven't been able to identify all issues but stability should be much better in one the latest builds on master. If you want to try this out, we generate a PHAR file with each build; in the Actions tab you can select a green build , click on it and find a link in the top right corner to download the phar file (under Artifacts).

We are now hard at work in stabilizing the application and will do a new alpha release once e are comfortable it works with as few issues as we can identify

**Comment by jaapio** [comment] 2020-01-16 10:11
Please check #2202 which fixes this issue. A new release will contain the fix. 
There are nightly builds available for a few weeks. Please consult the readme to see where to find them.

**Closed by jaapio** 2020-01-16 10:11 UTC
Labels: bug, research
