### ISSUE TITLE
Call to undefined function ContainerLx0j6hQ\include_once\dirname()

### ISSUE THREAD

**Issue by Ahmard** [phpDocumentor/phpDocumentor#2780] opened 2021-01-29 15:07 UTC
[WARNING] Some commands could not be registered:                               
                                                                                
In Filter_6ae6af3.php line 5:
                                                                      
  Call to undefined function ContainerLx0j6hQ\include_once\dirname()  
                                                             
  There are no commands defined in the "project" namespace.  

## Expected behavior

To work just fine

## Actual behavior

Error
## Steps to reproduce the problem

1. php Downloads/phpDocumentor.phar -d project -t project/docs

2.
3.

## Your environment

* Version used: 3.0.0-alpha1
*Install method: phar
* PHP version: 8.0.1
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): Ubuntu
* Link to your project:
* Attach code that is involved
* ...

![Screenshot from 2021-01-29 16-03-20](https://user-images.githubusercontent.com/44737217/106291628-2bfd7700-624c-11eb-9ce5-7167c70da563.png)

**Comment by jaapio** [comment] 2021-01-29 15:09
Duplicate of https://github.com/phpDocumentor/phpDocumentor/issues/2758

You are running phpDocumentor on php8, which isn't supported yet :-( I already addressed this issue in #2775  
And I hope we will be able to release a new version soon.

**Closed** 2021-01-29 15:09 UTC

**Comment by gizmore** [comment] 2021-03-06 00:11
How is the state of the phar install, regarding PHP8 ?
Can i use phpDocumentor when building a phar from latest snapshot?

Thanks!

**Comment by jaapio** [comment] 2021-03-06 06:41
Our latest version as described in the Readme as nightly build should run on php8. However we do not have support yet for all php8 syntax yet. Our internal parser needs an update. Which takes some time.
