### ISSUE TITLE
Error: null passed to phpDocumentor\Reflection\DocBlock\Tags\Formatter\PassthroughFormatter::format()

### ISSUE THREAD

**Issue by demiankatz** [phpDocumentor/phpDocumentor#2127] opened 2019-09-10 16:56 UTC
## Expected Behavior

I have been using PhpDoc on my project for many years, but the doc generation broke when I upgraded to PHP 7. I decided to try the latest alpha version, but this is also failing.

If I can do anything to assist with troubleshooting/data collecting, please let me know. I am happy to put some time into a solution and do not expect the project maintainers to do all the work. For now, though, I'm providing as much information as I can to get a conversation started about the issue!

## Actual Behavior

When running the 3.0.0-alpha.4 phar file, my output ends like this:

<pre>
[2019-09-10 16:48:20] php.CRITICAL: Fatal Error: Method phpDocumentor\Reflection\DocBlock\Description::__toString() must not throw an exception, caught TypeError: Argument 1 passed to phpDocumentor\Reflection\DocBlock\Tags\Formatter\PassthroughFormatter::format() must implement interface phpDocumentor\Reflection\DocBlock\Tag, null given, called in phar:///home/dkatz/vufind/vendor/bin/phpDocumentor-3.0.0-alpha.4.phar/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Description.php on line 92 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Method phpDocumentor\\Reflection\\DocBlock\\Description::__toString() must not throw an exception, caught TypeError: Argument 1 passed to phpDocumentor\\Reflection\\DocBlock\\Tags\\Formatter\\PassthroughFormatter::format() must implement interface phpDocumentor\\Reflection\\DocBlock\\Tag, null given, called in phar:///home/dkatz/vufind/vendor/bin/phpDocumentor-3.0.0-alpha.4.phar/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Description.php on line 92 at phar:///home/dkatz/vufind/vendor/bin/phpDocumentor-3.0.0-alpha.4.phar/src/phpDocumentor/Descriptor/DescriptorAbstract.php:0)"} []
[2019-09-10 16:48:20] php.CRITICAL: Fatal Error: Method phpDocumentor\Reflection\DocBlock\Description::__toString() must not throw an exception, caught TypeError: Argument 1 passed to phpDocumentor\Reflection\DocBlock\Tags\Formatter\PassthroughFormatter::format() must implement interface phpDocumentor\Reflection\DocBlock\Tag, null given, called in phar:///home/dkatz/vufind/vendor/bin/phpDocumentor-3.0.0-alpha.4.phar/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Description.php on line 92 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Method phpDocumentor\\Reflection\\DocBlock\\Description::__toString() must not throw an exception, caught TypeError: Argument 1 passed to phpDocumentor\\Reflection\\DocBlock\\Tags\\Formatter\\PassthroughFormatter::format() must implement interface phpDocumentor\\Reflection\\DocBlock\\Tag, null given, called in phar:///home/dkatz/vufind/vendor/bin/phpDocumentor-3.0.0-alpha.4.phar/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Description.php on line 92 at phar:///home/dkatz/vufind/vendor/bin/phpDocumentor-3.0.0-alpha.4.phar/src/phpDocumentor/Descriptor/DescriptorAbstract.php:0)"} []

In DescriptorAbstract.php line n/a:

  Error: Method phpDocumentor\Reflection\DocBlock\Description::__toString() must not throw an exception, caught TypeError: Argument 1 passed to phpDocumen
  tor\Reflection\DocBlock\Tags\Formatter\PassthroughFormatter::format() must implement interface phpDocumentor\Reflection\DocBlock\Tag, null given, called
   in phar:///home/dkatz/vufind/vendor/bin/phpDocumentor-3.0.0-alpha.4.phar/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Description.php on line
  92

</pre>

## Steps to Reproduce the Problem

  1. Clone my project's Git repo (https://github.com/vufind-org/vufind.git)
  2. Run composer install
  3. Edit build.xml to change the phpdoc version attribute (line 29) to 3.0.0-alpha.4
  4. Run `vendor/bin/phing phpdoc`

## Your environment

* Version used: 3.0.0-alpha4
* Install method: phar download
* php version: 7.1.30
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): Oracle Linux 7
* Link to your project: https://github.com/vufind-org/vufind

**Comment by jaapio** [comment] 2019-09-18 18:54
We need to figure out what description is causing this error. 
Currently, I'm trying to get more information by adding verbose flags `-vvvv` to phpdocumentor. 
Don't have any progress yet.

**Comment by demiankatz** [comment] 2019-09-18 18:59
@jaapio, I wonder if it would help to delete the majority of the project's files and then reintroduce them gradually to try to pinpoint the problem. If you don't make any progress on your end, please let me know and I will try this experiment the next time I have some free time!

**Comment by jaapio** [comment] 2019-09-18 19:29
Already found an issue. `module/VuFind/src/VuFind/Cache/Manager.php` contains a `@param` with a inline `@see`. For some reason the `@see` is processed wrong. 

I need to check if this is an issue in the handling of the `see` tag or if this is an invalid use case.

**Comment by jaapio** [comment] 2019-09-18 19:42
The problem you reported consists of two parts.
1. phpDocumentor crashes. This is obviously not correct.

2. You are using `@see` inline which is allowed, but you are referencing to a non-`FQSEN` it is not an url. So you are misusing `@see` here. I don't know how phpdoc2 was processing this previously. But since we are trying to be close to the upcoming phpdoc standard I don't think we can re-add this behavior. 
https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc-tags.md#512-see

**Comment by demiankatz** [comment] 2019-09-19 12:26
Thanks for the analysis, @jaapio, your help is very much appreciated!

As you say, it would be great for phpDocumentor to deal with malformed `@see` references more gracefully. In the meantime, though, I've cleaned up the problem documentation in my code, and now things appear to be working as expected. I'll leave this issue open for now, though -- I assume that if nothing else, my bad `@see` reference might be a good addition to the test suite for future reference.

Here's my commit fixing all of my questionable references, in case it matters: https://github.com/vufind-org/vufind/commit/a15a798de000d2495259d180214452a24d74619a

**Comment by oliverschloebe** [comment] 2019-12-10 14:49
Any news on this? As I'm trying to parse the WordPress source files I won't be able to edit the files causing the issue as they're being fetched automatically on a regular basis.

**Comment by jaapio** [comment] 2019-12-10 15:05
No progress on this one yet. But in the end, it is an issue in wordpress that should be fixed. we will ignore the invalid tags and continue the processing. 

If you want to speed up things you could consider to create a pr. I would be more than happy to guide you through that process.

**Comment by oliverschloebe** [comment] 2019-12-10 15:14
> We will ignore the invalid tags and continue the processing.

Actually that would be fine with me for now. Any idea where to start looking on how to ignore invalid tags?

Thank you!

**Comment by jaapio** [comment] 2019-12-10 15:22
The main issue is caused by the call to https://github.com/phpDocumentor/ReflectionDocBlock/blob/master/src/DocBlock/StandardTagFactory.php#L197 
Returning null will hide the errors in the process of processing docblocks. 
maybe just by adding a array_filter here: https://github.com/phpDocumentor/ReflectionDocBlock/blob/master/src/DocBlockFactory.php#L221 would already fix the issue.

**Comment by jaapio** [comment] 2020-01-16 10:37
A PR is in progress to fix this issue. Please follow #2209 to see the progress.

**Closed by jaapio** 2020-01-16 10:37 UTC
Labels: bug
