### ISSUE TITLE
Markdown isn't correctly handled for DSN class

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor#2635] opened 2020-10-18 09:48 UTC
When I viewed the DSN class during testing, I found out that the Markdown used there wasn't parsed correctly.

![image](https://user-images.githubusercontent.com/193704/96363934-c3c0d480-1137-11eb-9ca3-6fb5116aafd2.png)

## Expected behavior

HTML is not shown but instead handled

**Comment by jaapio** [comment] 2020-10-18 10:11
Hm this is odd... Would the new description filter be the cause of this issue?

**Comment by mvriel** [comment] 2020-10-18 10:27
I do not know; I haven't investigated this. Just reported this issue as I am busy fixing another bug :)

**Comment by jaapio** [comment] 2020-10-20 19:51
Fixed in https://github.com/phpDocumentor/phpDocumentor/commit/558410

**Closed by jaapio** 2020-10-20 19:51 UTC
Labels: bug, template
