### ISSUE TITLE
@internal is never rendered in template even with --parseprivate argument while building docs

### ISSUE THREAD

**Issue by henrotaym** [phpDocumentor/phpDocumentor#2310] opened 2020-03-13 11:58 UTC
I'm using the release candidate 3.0 version and I can't use the tag @internal properly.
 - Class property is indeed not parsed when building docs which is good.
 - When adding --parseprivate to building command, property is still not parsed.

Here is my property Docblock definition: 
    /**
     * OVH endpoint.
     * @internal
     */
    protected string $endPoint = 'ovh-eu';

Here is my command line executed which should parse @internal:
    phpdoc -d ./app/Voip -t public/docs --parseprivate

## Expected Behavior
I should see property informations if --parseprivate is added to command while building docs.

## Actual Behavior
Template never shows my property.

## Steps to Reproduce the Problem

  1. Create a dockblock for any function
  2. Add @internal tag 
  3. Generate documentation with --parseprivate argument

## Environment

* Version used: 3.0.0-rc
* Install method: using phar
* Theme: default
* php version: 7.4.3
* Operating system: windows 10

**Comment by mvriel** [comment] 2020-03-13 12:06
I'd need to double-check to be sure, but IIRC parseprivate will not render `@internal` by design. You'd need `--visibility=internal`. If that doesn't work, let me know and I'll dive into it deeper as soon as I have time.

**Comment by henrotaym** [comment] 2020-03-13 17:16
> I'd need to double-check to be sure, but IIRC parseprivate will not render `@internal` by design. You'd need `--visibility=internal`. If that doesn't work, let me know and I'll dive into it deeper as soon as I have time.

I tried but unfortunately, it's not working.

**Comment by jaapio** [comment] 2020-05-07 20:00
For now, you will have to specify `--visibility=public,proctect,private,internal`, I think you found a bug, that needs to be fixed. I will try to do that now.

**Comment by jaapio** [comment] 2020-05-08 20:09
This bug is fixed in master. And will be part of the next release

**Closed by jaapio** 2020-05-08 20:09 UTC
Labels: bug
