### ISSUE TITLE
v3.0.0-beta errors

### ISSUE THREAD

**Issue by thelounge-zz** [phpDocumentor/phpDocumentor#2250] opened 2020-02-02 12:40 UTC
Besides that the "old-ocean" had a way better organization of not namespaced sources:

In MethodDescriptor.php line 181:
  Return value of phpDocumentor\Descriptor\MethodDescriptor::getResponse() must be an instance of phpDocumentor\Descriptor\Tag\ReturnDescriptor, instance of phpDocumentor\
  Descriptor\TagDescriptor returned
  
In MethodDescriptor.php line 181:
  Return value of phpDocumentor\Descriptor\MethodDescriptor::getResponse() must be an instance of phpDocumentor\Descriptor\Tag\ReturnDescriptor, instance of phpDocumentor\
  Descriptor\TagDescriptor returned

**Comment by jaapio** [comment] 2020-02-02 13:50
Thanks for your report. This issue seems to be introduced with the introduction of `InvalidTag` in #2209, so this is a regression that needs to be fixed on our side.

However this is an issue on our side, this caused by an invalid formatted tag in your code which you might want to fix. According to the error you get I think there is a method with a `@return` tag which is not containing a valid `FQSEN` or malformed in another way. When phpDocumtor detects an invalid formatted tag it will catch the exception and replace it with a generic object containing the issue.

**Comment by thelounge-zz** [comment] 2020-02-02 14:06
surely, if it would tell me which of the 820 files should be fixed i would do so :-)

**Comment by thelounge-zz** [comment] 2020-02-02 15:54
well it was a "@return 0" which was simply correct because a dummy method always returned 0, change to int, so be it

**Comment by mvriel** [comment] 2020-02-02 16:06
As mentioned in the documentation, a return tag only supports a Type or one of the described pseudo-types or false. Any other value is unexpected. 

This tag should show up in the error report as an invalid use of the tag.

p.s. I am not sure what you mean by dummy method but if you mean that the method has no return statement than 'void' is the expected return type and practically it would be converted to `null` if you were to read it

**Comment by thelounge-zz** [comment] 2020-02-02 16:25
it's part of error handling and 0 is expected at this point, void would be wrong because the return value is later handed to a function expecting int and the real implementation of that class would also return 1

so technically it returns int but in that case it always retiurns 0

**Comment by mvriel** [comment] 2020-02-02 16:26
What you wrote down actually makes for a good description text for that `@return` tag :)

**Comment by jaapio** [comment] 2020-02-02 19:19
This issue has been fixed in master. Since the issue is also fixed by the author I'm closing this one.

**Closed by jaapio** 2020-02-02 19:19 UTC
Labels: bug
