### ISSUE TITLE
Unable to use custom template path

### ISSUE THREAD

**Issue by ADmad** [phpDocumentor/phpDocumentor#2117] opened 2019-08-17 13:27 UTC
Tried to specify custom template path:

```
php phpDocumentor.phar run -d src/ORM -t docs -e prod --template="/srv/sites/phpDocumentor2/data/templates/clean/"
```

Got error

```
Failed to copy "/srv/sites/phpDocumentor2/data/templates/clean/htaccess.dist" to "phar:///srv/sites/cake-apps/cakephp/phpDocumentor.phar/src/phpDocumentor/../../data/templates/cle  
  an/htaccess.dist" because target file could not be opened for writing.
```

* Version used: 3.0.0-alpha4
* phar

**Comment by ADmad** [comment] 2019-08-26 12:57
Trying to specify one of included templates doesn't work either https://github.com/phpDocumentor/phpDocumentor2/issues/2114#issuecomment-524848340

**Comment by mvriel** [comment] 2019-12-14 19:28
Thank you for reporting this issue; I have been able to locally verify it by downloading phpDocumentor.phar into my phpDocumentor folder and use the following command:

> ./phpDocumentor.phar --template=data/templates/clean

The issue is that in the past we explicitly copied the template files in one central folder so that you could re-use files from other templates. Unfortunately, this does not work when using a PHAR.

I do have a theory that this may not be needed anymore since we no longer use XSL and with Twig you can provide various base directories to include from. I do need to experiment to make that happen

**Comment by mvriel** [comment] 2019-12-22 09:20
@ADmad I have been doing a rework of how we address files so that it can actually read templates outside of the PHAR. I am not completely done (this has to do with how a phar sandboxes its files, and external templates work differently) but there is progress :)

**Comment by mvriel** [comment] 2020-01-27 10:56
There is progress in this issue; it now continues past your error but I am running into issues in the Twig loader now. We are working on it :)

**Comment by mvriel** [comment] 2020-01-27 12:15
Once finished, build https://github.com/phpDocumentor/phpDocumentor/actions/runs/31776448 will contain a PHAR file that should support external templates. I definitely need to do some more testing but hope you are able to help me there so that I can focus on solving more/other bugs in the mean time.

My initial tests have shown positive results; but I know I need more time to test this through in detail.

**Comment by jaapio** [comment] 2020-05-08 20:24
This issue is fixed now. and tested.

**Closed by jaapio** 2020-05-08 20:24 UTC
Labels: bug
