### ISSUE TITLE
Trait property FQDN resolution 

### ISSUE THREAD

**Issue by soyuka** [phpDocumentor/phpDocumentor#2213] opened 2020-01-20 16:41 UTC
##  Expected Behavior
Expected FQDN to resolve to `App\TraitLocation\TraitName`

## Actual Behavior

Resolves to `App\WhereTraitIsUsed\TraitName`

## Steps to Reproduce the Problem

Run the parser on the entity located in `src/Dummy.bak` from https://github.com/soyuka/self-referencing-metadata-api-platform

Original issue: https://github.com/api-platform/core/issues/3349

**Comment by jaapio** [comment] 2020-01-20 20:24
I'm sorry, also this one is not on our side. Also here I'm not sure how to fix this. The root cause is in `\ApiPlatform\Core\Bridge\Symfony\PropertyInfo\Metadata\Property\PropertyInfoPropertyMetadataFactory::create` 

This method is providing the defining class to the property-info component of symfony, which is used to instruct the DocBlockReflection component where the docblock is located. The input is always `App\Entity\Dummy` since the DocBlockReflection component is not aware of any context, it is processing one docblock at the time, It will use the context to discover the correct types. 
This is where things are getting messy.  Given the following example:

```
<?php
trait MyTrait {
    private $myTraitVar;
}
class MyClass {
    use MyTrait;
    private $myClassProp;
}
$reflectionClass = new ReflectionClass(MyClass::class);
foreach ($reflectionClass->getProperties() as $property) {
    var_dump($property->getDeclaringClass()->getName()); //always MyClass
}
```
So even php's reflection is not telling us the right location of the propery `myTraitVar` so based on the information we can get from what you are providing us we cannot detect the correct types. A more advanced way to produce the `Context` will be required. If the `Context` will contain a definition of `EventDispatcherInterface` it will work correctly. 

From phpDocumentor's perspective this is not an issue since we are processing one file at the time, and we will never include traits like you are doing now. However, I'm open to help if I can anything on our side. But I think we need to contact anyone in the symfony team to get this fixed.

**Comment by jaapio** [comment] 2020-01-20 20:29
Related to: https://github.com/symfony/symfony/issues/28732

**Comment by jaapio** [comment] 2020-01-20 20:32
Closing this one since there is a bug report on symfony for this issue. I think it should be solved on their side. If there is anything we can do to help please contact us.

**Closed by jaapio** 2020-01-20 20:32 UTC
Labels: research
