### ISSUE TITLE
Inline @see/@link are broken

### ISSUE THREAD

**Issue by donbidon** [phpDocumentor/phpDocumentor#1880] opened 2017-08-17 19:59 UTC
```php
/**
 * @param string $arg  {@link http://...}
 */
```
isn't processed and rendered as plain text.

**Comment by jaapio** [comment] 2017-08-18 18:13
Could you please provide us some more information about this finding?

**Comment by jaapio** [comment] 2017-08-22 14:33
@mbed67 could you check the status of this issue against the version in develop? Think you already solved it.

**Comment by mbed67** [comment] 2017-08-30 12:05
@jaapio @donBidon this is a way of using @see/@link I haven't thought of yet. However, it is indeed in the documentation that it can be used that way. It is broken, so I will see how to fix it.
<img width="637" alt="see link-issue" src="https://user-images.githubusercontent.com/7139949/29871491-3b28fff8-8d8c-11e7-8e3b-3d32a5c5f744.png">

**Comment by mvriel** [comment] 2020-02-12 20:23
closed as duplicate of #546

**Closed by mvriel** 2020-02-12 20:23 UTC
