### ISSUE TITLE
3.0.0: return types don't display anymore

### ISSUE THREAD

**Issue by jrfnl** [phpDocumentor/phpDocumentor#2463] opened 2020-06-20 00:55 UTC
Breakage introduced by 4a361515f12230cd08ed698937a75e3f380c0d32 in response to issue #2432 .

**Given the following piece of code in file `src/issue-2463.php`:**
``` php
<?php
class Issue2463
{
    /**
     * Method Summary.
     *
     * Long description.
     *
     * @since 1.0.0 Introduction version.
     *
     * @param \PHP_CodeSniffer\Files\File $phpcsFile The PHP_CodeSniffer file where the
     *                                               token was found.
     * @param int                         $openPtr   The position of the array opener token in the token stack.
     * @param int                         $closePtr  The position of the array closer token in the token stack.
     *
     * @return true|void Returning `TRUE` will short-circuit the sniff and stop processing.
     */
    public function processOpenClose(File $phpcsFile, $openPtr, $closePtr)
    {
    }
}
```

<details>
  <summary><b>with the following config:</b></summary>

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor
    configVersion="3"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://www.phpdoc.org"
    xsi:noNamespaceSchemaLocation="https://docs.phpdoc.org/latest/phpdoc.xsd"
>
    <title>Demo</title>
    <version number="latest">
        <api format="php">
            <source dsn=".">
                <path>src</path>
            </source>
        </api>
    </version>
    <template name="default"/>
</phpdocumentor>
```
</details>

## Expected behavior
I'd expect the return types to be displayed.

## Actual behavior
The return types don't display anymore.

### Rendering before (@ 748172c21f4c801701bb9cd0fe83d5b59ba427fd):

> ![issue-2462-before](https://user-images.githubusercontent.com/663378/85187661-5c863700-b2a1-11ea-90bf-9c5fa0ce96c6.png)

### Rendering at 4a361515f12230cd08ed698937a75e3f380c0d32:

> ![issue-2462-4a36151](https://user-images.githubusercontent.com/663378/85187660-5beda080-b2a1-11ea-97f2-cc45b9d49181.png)

## Steps to reproduce the problem

1. Issue can be reproduced with the above code sample and config.
2. Run `php -f /path/to/phpDocumentor/bin/phpdoc`

## Your environment

* Version used: phpDocumentor v3.0.x-dev@4a36151
* Install method: git clone
* PHP version: 7.4.6
* Operating system and version: Windows 7

**Comment by jaapio** [comment] 2020-06-20 06:40
Hm, I cannot reproduce this :thinking: 

![image](https://user-images.githubusercontent.com/1060433/85195325-a71fa780-b2d1-11ea-8a33-5914ec353681.png)

**Comment by jrfnl** [comment] 2020-06-20 06:50
Which cache do you mean ?

I ran `phpdoc cache:clear --env=prod` in the phpDocumentor install directory + did a `composer install` before I did the regen.

Do you mean the output cache ?

**Comment by jaapio** [comment] 2020-06-20 06:52
Yes, I meant the output cache. 
Anyhow #2462 seems to be an issue... so I'm still working on both issues now. To see what is actually going on :-(

**Comment by jrfnl** [comment] 2020-06-20 07:02
Ok, threw away the complete `.phpdoc` directory (docs + cache) and I can confirm that fixes it, though that does bring me back to #2429...

**Comment by jaapio** [comment] 2020-06-20 07:05
Thanks for the confirmation. Closing this one. 
We can discuss in the other issues what needs to be done to make this behavior better.

**Closed by jaapio** 2020-06-20 07:05 UTC
Labels: bug, needs author update

**Comment by mvriel** [comment] 2020-06-20 07:06
#2429 is irrelevant in this situation; cache is already cleared in certain scenarios

**Comment by jaapio** [comment] 2020-06-20 07:07
Yes, but not when we are changing things :-D Still wonder how this could have happened
