### ISSUE TITLE
v3.0.0-beta: an error was detected: The tag "@example ['List-Unsubscribe', 'List-Help']" does not seem to be wellformed, please check it for errors

### ISSUE THREAD

**Issue by thelounge-zz** [phpDocumentor/phpDocumentor#2260] opened 2020-02-03 09:35 UTC
09:32:21 ALERT     [app]   Unable to parse file "global_class.phpmailer.php", an error was detected: The tag "@example ['List-Unsubscribe', 'List-Help']" does not seem to be wellformed, please check it for errors

@example ['List-Unsubscribe', 'List-Help']

the @see, @example and @uses are way too sensible, i removed them finally from my codebase but phpmailer is upstream 3rd party code (listet in --ignore until now)

**Comment by jaapio** [comment] 2020-02-07 21:02
I'm closing this issue because it is caused by an already reported issue in docblock-reflection. The tag usage is invalid. But because we are now more strict this causes issues in phpDocumentor. We cannot fix this in phpDocumentor because the docblock processing stops so it will need to be fixed in an other lib. However I'm very unsure how to fix this. 
 
https://github.com/phpDocumentor/ReflectionDocBlock/issues/165

**Comment by mvriel** [comment] 2020-02-08 18:32
We are looking into improving the pattern matching in our DocBlock parser to prevent this error from happening. We will give a heads up as soon as that lands in phpDocumentor

**Comment by jaapio** [comment] 2020-02-09 10:15
This one is now also fixed in master.
I will start preparing a new release now since all reported bugs are now fixed.

**Closed by jaapio** 2020-02-09 10:15 UTC
Labels: bug
