### ISSUE TITLE
v3.0.0-beta; @todo is ignored

### ISSUE THREAD

**Issue by thelounge-zz** [phpDocumentor/phpDocumentor#2256] opened 2020-02-02 16:57 UTC
3.0.0-beta looks nearly as it could be a RC, besides some other small issues @todo Tags are ignored

Deprecated
Errors
Markers

all 3 are empty, i would expect it below "Markers"

**Comment by jaapio** [comment] 2020-02-02 20:05
Thanks for reporting this. 
I found a bug in the processing of inline markers. And a number of issues in our new template regarding makers. All is fixed in master. And will be released with the other issues you reported.

**Comment by Yivan** [comment] 2020-02-19 14:49
Hello @jaapio 

Thanks for this wonderful v3!

Just to say same issue here with simple php file on v3.0.0-rc:

```
<?php

// TODO: faire cela
echo "ok";

```

Runned with:
`php /var/www/html/tests/phar/phpDocumentor.phar -d /var/www/html/src/ -t docs/phpDocumentor`

The TODO list in the HTML report is empty.
I think it is corrected as you said, but I can only try with phar version which is not already patched I imagine.
This was just to report my use case and be sure it is the same issue than this one. As it is a Release Candidate I am not sure...

By the way maybe linked to https://github.com/phpDocumentor/phpDocumentor/issues/2060 which could be closed too.

Thanks!

**Comment by Yivan** [comment] 2020-02-19 14:59
EDIT: tested with the docker image 3 (released 3 days ago at this date), and Marker list is empty too on the report.

**Comment by mvriel** [comment] 2020-02-19 15:01
Reopening issue for further investigation

**Comment by Yivan** [comment] 2020-02-19 15:55
@mvriel 
Got it, it need the "--sourcecode" parameters. Without this, TODO are not parsed.
Maybe it should be added to doc or if this is a bug should be fixed.
Thanks.

**Comment by thelounge-zz** [comment] 2020-02-19 16:35
// TODO: faire cela
is a different beast as
@todo in a docblock which never starts with // at all

**Comment by jaapio** [comment] 2020-02-19 18:58
The main issue with excluding the sources is that phpdocumentor cannot read the source during the compilation process of the documentation. I think this is not a bug. But it is a missing piece in our own docs. If you think of it you could even explain this as a feature. Sometimes you want to expose your api only, and not all internal to do items.

I checked this with v2 and the behavior is different. V2 just added all todo's the only way to remove them from the docs was to remove the markers from the config.

I would like to have your input on what you would expect phpdocumentor would do by default.

One thing that is clear to me is that we need to document this

**Comment by Yivan** [comment] 2020-02-19 20:54
If I can give my advice @jaapio , I would go for only updating the doc (and the help in CLI) just to say the flag --source is necessary for markers.
As a plus, and if easy, if --marker or custom marker is set in config files, automatically add source.
Just my point of view.
Thanks a lot for having so fast answered! : )

**Comment by thelounge-zz** [comment] 2020-02-19 21:29
i woukd prefer *any* useful comment within the documentaion but *not* --sourcecode because i don't want to leak the complete source itself as part of the docs

**Comment by jaapio** [comment] 2020-02-20 07:37
Would you even want expose your todo's at source code level if you don't want to expose the source code?

**Comment by thelounge-zz** [comment] 2020-02-20 07:43
of course

**Comment by jaapio** [comment] 2021-06-04 15:41
I fixed this in https://github.com/phpDocumentor/phpDocumentor/pull/2919 will be part of phpdocumentor 3.1

**Closed by jaapio** 2021-06-04 15:41 UTC
Labels: bug
