### ISSUE TITLE
Parsing phpBB 3.3.0 source code triggers a bunch of phpDocumentator errors

### ISSUE THREAD

**Issue by flip111** [phpDocumentor/phpDocumentor#2331] opened 2020-04-13 13:46 UTC
```
» php phpDocumentor.phar -d .
phpDocumentor v3.0.0-rc

Parsing files
   86/2994 [>---------------------------]   2%15:43:38 ALERT     [app]   Unable to parse file "includes/functions.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:43:38 ALERT     [app]   Unable to parse file "includes/functions.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
  319/2994 [==>-------------------------]  10%15:43:49 ALERT     [app]   Unable to parse file "phpbb/config/config.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:43:49 ALERT     [app]   Unable to parse file "phpbb/config/config.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:43:50 ALERT     [app]   Unable to parse file "phpbb/content_visibility.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:43:50 ALERT     [app]   Unable to parse file "phpbb/content_visibility.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
  599/2994 [=====>----------------------]  20%15:43:53 ALERT     [app]   Unable to parse file "phpbb/error_collector.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:43:53 ALERT     [app]   Unable to parse file "phpbb/error_collector.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
  899/2994 [========>-------------------]  30%15:43:56 ALERT     [app]   Unable to parse file "phpbb/request/deactivated_super_global.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:43:56 ALERT     [app]   Unable to parse file "phpbb/request/deactivated_super_global.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:43:56 ALERT     [app]   Unable to parse file "phpbb/request/request.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:43:56 ALERT     [app]   Unable to parse file "phpbb/request/request.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:43:56 ALERT     [app]   Unable to parse file "phpbb/request/request_interface.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:43:56 ALERT     [app]   Unable to parse file "phpbb/request/request_interface.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
 1198/2994 [===========>----------------]  40%15:44:00 ALERT     [app]   Unable to parse file "vendor/lusitanian/oauth/src/OAuth/OAuth2/Service/Buffer.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:00 ALERT     [app]   Unable to parse file "vendor/lusitanian/oauth/src/OAuth/OAuth2/Service/Buffer.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:01 ALERT     [app]   Unable to parse file "vendor/lusitanian/oauth/src/OAuth/OAuth2/Service/Paypal.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:01 ALERT     [app]   Unable to parse file "vendor/lusitanian/oauth/src/OAuth/OAuth2/Service/Paypal.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:01 ALERT     [app]   Unable to parse file "vendor/ocramius/package-versions/src/PackageVersions/FallbackVersions.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:01 ALERT     [app]   Unable to parse file "vendor/ocramius/package-versions/src/PackageVersions/FallbackVersions.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
 1324/2994 [============>---------------]  44%15:44:02 ALERT     [app]   Unable to parse file "vendor/ralouphie/getallheaders/src/getallheaders.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:02 ALERT     [app]   Unable to parse file "vendor/ralouphie/getallheaders/src/getallheaders.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
 1497/2994 [==============>-------------]  50%15:44:03 ALERT     [app]   Unable to parse file "vendor/s9e/text-formatter/src/Configurator/Collections/Ruleset.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:03 ALERT     [app]   Unable to parse file "vendor/s9e/text-formatter/src/Configurator/Collections/Ruleset.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:03 ALERT     [app]   Unable to parse file "vendor/s9e/text-formatter/src/Configurator/Helpers/ElementInspector.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:03 ALERT     [app]   Unable to parse file "vendor/s9e/text-formatter/src/Configurator/Helpers/ElementInspector.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
 1716/2994 [================>-----------]  57%15:44:05 ALERT     [app]   Unable to parse file "vendor/s9e/text-formatter/src/Plugins/HTMLElements/Configurator.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:05 ALERT     [app]   Unable to parse file "vendor/s9e/text-formatter/src/Plugins/HTMLElements/Configurator.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
 1797/2994 [================>-----------]  60%15:44:06 ALERT     [app]   Unable to parse file "vendor/symfony/config/Definition/Builder/NodeBuilder.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:06 ALERT     [app]   Unable to parse file "vendor/symfony/config/Definition/Builder/NodeBuilder.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:06 ALERT     [app]   Unable to parse file "vendor/symfony/config/Exception/FileLocatorFileNotFoundException.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:06 ALERT     [app]   Unable to parse file "vendor/symfony/config/Exception/FileLocatorFileNotFoundException.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
 1912/2994 [=================>----------]  63%15:44:07 ALERT     [app]   Unable to parse file "vendor/symfony/console/Output/NullOutput.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:07 ALERT     [app]   Unable to parse file "vendor/symfony/console/Output/NullOutput.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
 2172/2994 [====================>-------]  72%15:44:10 ALERT     [app]   Unable to parse file "vendor/symfony/http-foundation/IpUtils.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:10 ALERT     [app]   Unable to parse file "vendor/symfony/http-foundation/IpUtils.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:10 ALERT     [app]   Unable to parse file "vendor/symfony/http-foundation/Session/Storage/Handler/PdoSessionHandler.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:10 ALERT     [app]   Unable to parse file "vendor/symfony/http-foundation/Session/Storage/Handler/PdoSessionHandler.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
 2254/2994 [=====================>------]  75%15:44:11 ALERT     [app]   Unable to parse file "vendor/symfony/http-kernel/EventListener/SaveSessionListener.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:11 ALERT     [app]   Unable to parse file "vendor/symfony/http-kernel/EventListener/SaveSessionListener.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
 2396/2994 [======================>-----]  80%15:44:12 ALERT     [app]   Unable to parse file "vendor/symfony/routing/Generator/ConfigurableRequirementsInterface.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:12 ALERT     [app]   Unable to parse file "vendor/symfony/routing/Generator/ConfigurableRequirementsInterface.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:12 ALERT     [app]   Unable to parse file "vendor/symfony/routing/Generator/Dumper/PhpGeneratorDumper.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:12 ALERT     [app]   Unable to parse file "vendor/symfony/routing/Generator/Dumper/PhpGeneratorDumper.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:12 ALERT     [app]   Unable to parse file "vendor/symfony/routing/Generator/UrlGenerator.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:12 ALERT     [app]   Unable to parse file "vendor/symfony/routing/Generator/UrlGenerator.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:12 ALERT     [app]   Unable to parse file "vendor/symfony/routing/Generator/UrlGeneratorInterface.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:12 ALERT     [app]   Unable to parse file "vendor/symfony/routing/Generator/UrlGeneratorInterface.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:13 ALERT     [app]   Unable to parse file "vendor/symfony/routing/Loader/XmlFileLoader.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:13 ALERT     [app]   Unable to parse file "vendor/symfony/routing/Loader/XmlFileLoader.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:13 ALERT     [app]   Unable to parse file "vendor/symfony/routing/Loader/YamlFileLoader.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:13 ALERT     [app]   Unable to parse file "vendor/symfony/routing/Loader/YamlFileLoader.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:13 ALERT     [app]   Unable to parse file "vendor/symfony/routing/Matcher/Dumper/PhpMatcherDumper.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:13 ALERT     [app]   Unable to parse file "vendor/symfony/routing/Matcher/Dumper/PhpMatcherDumper.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:13 ALERT     [app]   Unable to parse file "vendor/symfony/routing/RequestContext.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:13 ALERT     [app]   Unable to parse file "vendor/symfony/routing/RequestContext.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:13 ALERT     [app]   Unable to parse file "vendor/symfony/routing/Route.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:13 ALERT     [app]   Unable to parse file "vendor/symfony/routing/Route.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:13 ALERT     [app]   Unable to parse file "vendor/symfony/routing/RouteCollection.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:13 ALERT     [app]   Unable to parse file "vendor/symfony/routing/RouteCollection.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:13 ALERT     [app]   Unable to parse file "vendor/symfony/routing/RouteCompiler.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
15:44:13 ALERT     [app]   Unable to parse file "vendor/symfony/routing/RouteCompiler.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
 2695/2994 [=========================>--]  90%15:44:14 ALERT     [app]   Unable to parse file "vendor/twig/twig/src/Extension/CoreExtension.php", an error was detected: "" is not a valid Fqsen.
15:44:14 ALERT     [app]   Unable to parse file "vendor/twig/twig/src/Extension/CoreExtension.php", an error was detected: "" is not a valid Fqsen.
15:44:14 ALERT     [app]   Unable to parse file "vendor/twig/twig/src/Extension/DebugExtension.php", an error was detected: "" is not a valid Fqsen.
15:44:14 ALERT     [app]   Unable to parse file "vendor/twig/twig/src/Extension/DebugExtension.php", an error was detected: "" is not a valid Fqsen.
15:44:14 ALERT     [app]   Unable to parse file "vendor/twig/twig/src/Extension/EscaperExtension.php", an error was detected: "" is not a valid Fqsen.
15:44:14 ALERT     [app]   Unable to parse file "vendor/twig/twig/src/Extension/EscaperExtension.php", an error was detected: "" is not a valid Fqsen.
15:44:14 ALERT     [app]   Unable to parse file "vendor/twig/twig/src/Extension/StringLoaderExtension.php", an error was detected: "" is not a valid Fqsen.
15:44:14 ALERT     [app]   Unable to parse file "vendor/twig/twig/src/Extension/StringLoaderExtension.php", an error was detected: "" is not a valid Fqsen.
 2994/2994 [============================] 100%15:44:25 ERROR     [console] Error thrown while running command "-d '.'". Message: "Call to undefined method phpDocumentor\Reflection\Fqsen::getMethods()" ["exception" => Error { …},"command" => "-d '.'","message" => "Call to undefined method phpDocumentor\Reflection\Fqsen::getMethods()"]
15:44:25 ERROR     [console] Error thrown while running command "-d '.'". Message: "Call to undefined method phpDocumentor\Reflection\Fqsen::getMethods()" ["exception" => Error { …},"command" => "-d '.'","message" => "Call to undefined method phpDocumentor\Reflection\Fqsen::getMethods()"]

In MethodDescriptor.php line 241:
                                                                                                       
  Attempted to call an undefined method named "getMethods" of class "phpDocumentor\Reflection\Fqsen".  
                                                                                                       

project:run [-t|--target [TARGET]] [--cache-folder [CACHE-FOLDER]] [-f|--filename [FILENAME]] [-d|--directory [DIRECTORY]] [--encoding [ENCODING]] [--extensions [EXTENSIONS]] [-i|--ignore [IGNORE]] [--ignore-tags [IGNORE-TAGS]] [--hidden] [--ignore-symlinks] [-m|--markers [MARKERS]] [--title [TITLE]] [--force] [--validate] [--visibility [VISIBILITY]] [--defaultpackagename [DEFAULTPACKAGENAME]] [--sourcecode] [--template [TEMPLATE]] [-s|--setting [SETTING]] [--list-settings] [--parseprivate] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-c|--config [CONFIG]] [--log [LOG]] [-e|--env ENV] [--no-debug] [--] <command>
```

**Comment by jaapio** [comment] 2020-04-13 14:34
Hi,
Thanks for reporting this. Could you give our nightly build a try? The Readme of this project tells you where to get it. That might solve the issues you are now experiencing.

A number of bugs have been fixed in the nightly build I'm not sure if this particular issue has been resolved. But I would be very grateful if you could let us know if that solved the problem.

**Comment by flip111** [comment] 2020-04-13 16:22
source code can be downloaded here https://download.phpbb.com/pub/release/3.3/3.3.0/phpBB-3.3.0.zip

---

https://github.com/phpDocumentor/phpDocumentor/actions/runs/64641141

```
phpDocumentor 050a5ab

Parsing files
 2996/2996 [============================] 100%
Applying transformations (can take a while)
  6/19 [========>-------------------]  31%18:18:52 ERROR     [console] Error thrown while running command "-d '.'". Message: "An exception has been thrown during the rendering of a template (""\GuzzleHttp\Psr7\StreamDecoratorTrait::$" is not a valid Fqsen.")." ["exception" => Twig\Error\RuntimeError^ { …},"command" => "-d '.'","message" => "An exception has been thrown during the rendering of a template (""\GuzzleHttp\Psr7\StreamDecoratorTrait::$" is not a valid Fqsen.")."]
18:18:52 ERROR     [console] Error thrown while running command "-d '.'". Message: "An exception has been thrown during the rendering of a template (""\GuzzleHttp\Psr7\StreamDecoratorTrait::$" is not a valid Fqsen.")." ["exception" => Twig\Error\RuntimeError^ { …},"command" => "-d '.'","message" => "An exception has been thrown during the rendering of a template (""\GuzzleHttp\Psr7\StreamDecoratorTrait::$" is not a valid Fqsen.")."]

In trait.html.twig line 37:
                                                                                                                                         
  An exception has been thrown during the rendering of a template (""\GuzzleHttp\Psr7\StreamDecoratorTrait::$" is not a valid Fqsen.").  
                                                                                                                                         

In Fqsen.php line 51:
                                                                    
  "\GuzzleHttp\Psr7\StreamDecoratorTrait::$" is not a valid Fqsen.  
                                                                    

project:run [-t|--target [TARGET]] [--cache-folder [CACHE-FOLDER]] [-f|--filename [FILENAME]] [-d|--directory [DIRECTORY]] [--encoding [ENCODING]] [--extensions [EXTENSIONS]] [-i|--ignore [IGNORE]] [--ignore-tags [IGNORE-TAGS]] [--hidden] [--ignore-symlinks] [-m|--markers [MARKERS]] [--title [TITLE]] [--force] [--validate] [--visibility [VISIBILITY]] [--defaultpackagename [DEFAULTPACKAGENAME]] [--sourcecode] [--template [TEMPLATE]] [-s|--setting [SETTING]] [--list-settings] [--parseprivate] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-c|--config [CONFIG]] [--log [LOG]] [-e|--env ENV] [--no-debug] [--] <command>
```

**Closed** 2020-05-05 10:23 UTC

**Comment by jaapio** [comment] 2020-05-05 10:24
The issue was caused by an invalid tag in guzzle. I added a fix to phpdocumentor to ensure this is not causing a crash.

please check the nightly build of the commit I referenced to this issue to see if that works for you.

**Comment by flip111** [comment] 2020-05-06 10:12
I'm a bit out of context for this (my) project at the moment. I believe you that it works on your side.

**Comment by caranaperu** [comment] 2020-08-16 21:33
I found the problem in a methos that doesnt had params or return , but i put and @see as unique tag
