### ISSUE TITLE
@var handling does not work without element name

### ISSUE THREAD

**Issue by splitbrain** [phpDocumentor/phpDocumentor#2808] opened 2021-02-05 23:35 UTC
The [Tag Reference](https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/var.html#var) for the `@var` tag says:

> The `@var` tag MUST contain the name of the element it documents. **An exception to this is when a declaration only refers to a single property or constant. In that case, the name of the property or constant MAY be omitted.**

The latter seems not to work. Here's a simple class with a single property and a doc block as auto-completed by PHPStorm:

```php
<?php

class Test {

    /** @var int This text should be shown */
    public $test = 5;
}
```

This is the result (using the latest available .phar as of today):

![2021-02-06-002711_888x595_scrot](https://user-images.githubusercontent.com/86426/107099663-94cb8d00-6812-11eb-8b75-22a4931b71f7.png)

## Expected behavior

I would expect the descriptive text for the test property "This text should be shown" to be visible in the docs.

## Actual behavior

No text is available for the property.

## Steps to reproduce the problem

1. create a `test.php` file with the above contents
2. run `php7 phpDocumentor.phar -f test.php -t docs`

## Environment

* Version used: v3.0.0
* Install method: phar
* PHP version: 7.4.15
* Operating system and version: Arch Linux

**Comment by jaapio** [comment] 2021-04-23 15:54
I think this is a duplicate of #2820 Will check this with some tests.

**Closed by jaapio** 2021-04-23 15:54 UTC
